### ISSUE TITLE
Split Table examples into sub pages

### ISSUE THREAD

**Issue by kevinch** [vtex/styleguide#1007]
Examples could all have their own pages and the Table's readme could be a summary of those examples with the main principles of the Table.

**Comment by arthurepc** [comment]
Is this for the experimental table only or for both? Maybe the experimental table should already become non-experimental. What do you guys think? @matheusps @kevinch

**Comment by matheusps** [comment]
@arthurepc ,

**Comment by matheusps** [comment]
I though supposed to be done just in v2 (which already is). Reopening because it may still be wanted on v1.

**Comment by jonathasbsouza** [comment]
As we will deprecate Table v1, I think we can reclose this issue, @matheusps

**Comment by matheusps** [comment]
yes, it can be done @jonathasbsouza
