### ISSUE TITLE
the icons don't work

### ISSUE THREAD

**Issue by Mecrano** [vtex/styleguide#1019]
**Describe the bug**
When I try to import any icon, it throws me an error saying that it does not exist

**To Reproduce**
1. import styleguide on manifest.json ("vtex.styleguide": "9.x")
2. Go to Component.tsx
3. import icon ShoppingCart (import { ShoppingCart, Delete } from 'vtex.styleguide')
4. When page render you see error

**Expected behavior**
display icons correctly

**Screenshots**
Import:
![image](https://user-images.githubusercontent.com/26680887/73403523-99836a00-42bd-11ea-88d1-406c4e07cb86.png)

Error:
![image](https://user-images.githubusercontent.com/26680887/73403565-aef89400-42bd-11ea-9ae1-83258f3a5f81.png)

Usage:
![image](https://user-images.githubusercontent.com/26680887/73403665-ecf5b800-42bd-11ea-9adb-72f9b859e42c.png)

**Additional context**
Null

**Comment by matheusps** [comment]
@Mecrano, try to import as:
`import { IconShoppingCart, IconDelete } from 'vtex.styleguide'`

**Comment by Mecrano** [comment]
@matheusps , now it is working, I guess the documentation is not very clear on how to import these icons, I suggest maybe give some example, thanks to you, I close the issue

### Solution:

**- Import icons:**
```
import { IconDelete } from 'vtex.styleguide'
```

**- Use:**
```
<ButtonWithIcon
  onClick={anyfunction}
  variation="primary"
  icon={<IconDelete />}
>
     Remove
</ButtonWithIcon>
```
