### ISSUE TITLE
Card - ajustes

### ISSUE THREAD

**Issue by cmdalbem** [vtex/styleguide#103]
- [ ] Resolver o problema da margem superior quando usa o modo `full-width` com uma imagem e sem título
- [ ] Adicionar um `w-100` pro card ocupar inteiramente o tamanho do container

Design: https://www.figma.com/file/a94lX91ZmYGIDBxvb8shwLn8/VTEX-Design?node-id=148%3A962

**Comment by cmdalbem** [comment]
Design: https://www.figma.com/file/a94lX91ZmYGIDBxvb8shwLn8/VTEX-Design?node-id=148%3A962

**Comment by lbebber** [comment]
Acho que talvez faça sentido mudar de `fullWidth`—que só diz respeito à largura—para algo como `noPadding`—que remova em ambas dimensões. Alem disso, acho que fica mais claro o que a propriedade faz.
