### ISSUE TITLE
Figma Design Kit

### ISSUE THREAD

**Issue by stas** [vtex/styleguide#1107]
**Describe the bug**

The link to the design kit is leading to a 404 page.

**To Reproduce**

Go to https://styleguide.vtex.com/#/Introduction/Designing
Find the *Figma Design Kit*, click on it.

**Expected behavior**

Load the page with the kit :)

**Comment by jonathasbsouza** [comment]
Hey @stas , I think now you can access the file without any problem.

**Comment by stas** [comment]
Obrigado! :bowing_man:
