### ISSUE TITLE
Update documentation examples

### ISSUE THREAD

**Issue by kevinch** [vtex/styleguide#1124]
IMO it does not make sense to have non-functional examples of the components in our docs.

- [x] ActionMenu
- [x] Alert
- [x] AutocompleteInput
- [x] Box
- [x] Button
- [x] ButtonGroup
- [x] ButtonPlain
- [x] ButtonWithIcon
- [x] Card
- [x] Checkbox
- [x] CheckboxGroup
- [x] Collapsible
- [x] ColorPicker
- [x] Conditions
- [x] DatePicker
- [x] Divider
- [x] Dropdown
- [x] Dropzone
- [x] EmptyState
- [x] EXPERIMENTAL_Charts
- - [x] BarChart
- - [x] BubbleChart
- - [x] LineChart
- - [x] ScatterChart
- [x] EXPERIMENTAL_Conditions
- [x] EXPERIMENTAL_Select
- [x] EXPERIMENTAL_Table
- [x] EXPERIMENTAL_TableTree
- [x] EXPERIMENTAL_useCheckboxTree
- [x] FilterBar
- [ ] FilterOptions
- [x] FloatingActionBar
- [x] icon
- [x] Input
- [x] InputButton
- [x] InputCurrency
- [x] InputPassword
- [x] InputSearch
- [x] Layout
- [x] Link
- [x] Menu
- [x] Modal
- [x] ModalDialog
- [x] NumericStepper
- [x] PageBlock
- [x] PageHeader
- [x] Pagination
- [x] Progress
- - [x] Line
- - [x] Steps
- [x] Radio
- [x] RadioGroup
- [x] SelectableCard
- [x] Slider
- [x] Spinner
- [x] Statement
- [x] Tab **[N/A]**
- [x] Table
- [x] Tabs
- [x] Tag
- [x] Textarea
- [x] TimePicker
- [x] ToastProvider
- [x] Toggle
- [x] Tooltip
- [x] Totalizer

**Comment by kevinch** [comment]
`Card`: https://github.com/vtex/styleguide/pull/1125

**Comment by kevinch** [comment]
`Divider`: https://github.com/vtex/styleguide/pull/1126

**Comment by kevinch** [comment]
`Link`: https://github.com/vtex/styleguide/pull/1127

**Comment by kevinch** [comment]
`Datepicker`, `Pagination`, `Textarea`, `Tooltip` & `Totalizer`: https://github.com/vtex/styleguide/pull/1128

**Comment by cmdalbem** [comment]
omg amazing to see this huge work is under way!
are we also aiming to update all "business" examples with E-commerce themes, as in the original issue (https://github.com/vtex/styleguide/issues/380)?

**Comment by kevinch** [comment]
@cmdalbem i'm currently focusing on fixing weak examples and non-functional ones. But i'd love some help to apply the eCommerce theme all around yes as you stated in the 380 issue.

**Comment by kevinch** [comment]
**Second step, add eCommerce related examples:**

- [ ] ActionMenu
- [ ] Alert
- [ ] AutocompleteInput
- [ ] Box
- [ ] Button
- [ ] ButtonGroup
- [ ] ButtonPlain
- [ ] ButtonWithIcon
- [ ] Card **[WIP]**
- [ ] Checkbox
- [ ] CheckboxGroup
- [ ] Collapsible
- [ ] ColorPicker
- [ ] Conditions
- [ ] DatePicker **[WIP]**
- [ ] Divider **[WIP]**
- [ ] Dropdown
- [ ] Dropzone
- [ ] EmptyState
- [ ] EXPERIMENTAL_Charts
- - [ ] BarChart
- - [ ] BubbleChart
- - [ ] LineChart
- - [ ] ScatterChart
- [ ] EXPERIMENTAL_Conditions
- [ ] EXPERIMENTAL_Select
- [ ] EXPERIMENTAL_Table
- [ ] EXPERIMENTAL_TableTree
- [ ] EXPERIMENTAL_useCheckboxTree
- [ ] FilterBar
- [ ] FilterOptions
- [ ] FloatingActionBar
- [ ] icon
- [ ] Input
- [ ] InputButton
- [ ] InputCurrency
- [ ] InputPassword
- [ ] InputSearch
- [ ] Layout
- [ ] Link
- [ ] Menu
- [ ] Modal
- [ ] ModalDialog
- [ ] NumericStepper
- [ ] PageBlock
- [ ] PageHeader
- [ ] Pagination **[WIP]**
- [ ] Progress
- - [ ] Line
- - [ ] Steps
- [ ] Radio
- [ ] RadioGroup
- [ ] SelectableCard
- [ ] Slider
- [ ] Spinner
- [ ] Statement
- [ ] Tab
- [ ] Table
- [ ] Tabs
- [ ] Tag
- [ ] Textarea **[WIP]**
- [ ] TimePicker
- [ ] ToastProvider
- [ ] Toggle
- [ ] Tooltip **[WIP]**
- [ ] Totalizer **[WIP]**

**Comment by kevinch** [comment]
`ButtonGroup` small fix: https://github.com/vtex/styleguide/pull/1133

**Comment by kevinch** [comment]
`ButtonPlain`: https://github.com/vtex/styleguide/pull/1134

**Comment by kevinch** [comment]
`NumericStepper`: https://github.com/vtex/styleguide/pull/1135

**Comment by kevinch** [comment]
`InputCurrency`: https://github.com/vtex/styleguide/pull/1140

**Comment by kevinch** [comment]
`Dropzone`: https://github.com/vtex/styleguide/pull/1141

**Comment by kevinch** [comment]
`Datepicker` & `Toatalizer`: https://github.com/vtex/styleguide/pull/1145

**Comment by kevinch** [comment]
`Collapsible`: https://github.com/vtex/styleguide/pull/1155

**Comment by kevinch** [comment]
`Box`: https://github.com/vtex/styleguide/pull/1162

**Comment by kevinch** [comment]
`Modal`: https://github.com/vtex/styleguide/pull/1164

**Comment by kevinch** [comment]
`ModalDialog`: https://github.com/vtex/styleguide/pull/1168

**Comment by kevinch** [comment]
`Dropdown`: https://github.com/vtex/styleguide/pull/1170

**Comment by kevinch** [comment]
`RadioGroup`: https://github.com/vtex/styleguide/pull/1185

**Comment by kevinch** [comment]
`Table`: https://github.com/vtex/styleguide/pull/1186

**Comment by kevinch** [comment]
`Tabs`: https://github.com/vtex/styleguide/pull/1187

**Comment by kevinch** [comment]
`Colorpicker`: https://github.com/vtex/styleguide/pull/1188

**Comment by emersonlaurentino** [comment]
@kevinch can u close this issue?

**Comment by jonathasbsouza** [comment]
@emersonlaurentino I think we didn't update `FilterOptions`

**Comment by kevinch** [comment]
Closing since we did not get a return on just one specific item.
