### ISSUE TITLE
First Dropdown's option keep selected when set value to undefined

### ISSUE THREAD

**Issue by ThaynanAndrey** [vtex/styleguide#1131]
**Describe the bug**
When I select undefined as the value of Dropdown, shows the first option on Dropdown as selected.

**To Reproduce**

1. Render Dropdown with value other than undefined;
2. Set value to undefined;
3. Open Dropdown's options;
4. Observe that firt option is selected.

**Expected behavior**
No option should be selected

**Comment by emersonlaurentino** [comment]
fixed in #1132
