### ISSUE TITLE
PageBlock and Box components should have "stretch" variation

### ISSUE THREAD

**Issue by estacioneto** [vtex/styleguide#1147]
**Describe the bug**

We have no way of making a `PageBlock` component fill its parent's height.
Also, shouldn't the `aside` variation be able to stretch blocks and make them the same height?

**To Reproduce**

Just create two `PageBlock` components, side by side, and make one of them be bigger than the other one. E.g.:

![image](https://user-images.githubusercontent.com/15948386/78382757-b7b36200-75ad-11ea-8d78-f37b23b38426.png)

**Expected behavior**

![image](https://user-images.githubusercontent.com/15948386/78382810-ca2d9b80-75ad-11ea-87fb-6c4caf6a5e4c.png)

**Comment by estacioneto** [comment]
Some code to help...

![image](https://user-images.githubusercontent.com/15948386/78383178-593ab380-75ae-11ea-8d7b-1bc429314d9a.png)

This is what I needed to do so the boxes got the same height to put it in the PR description.

P.S.: I'm using two `PageBlock` components instead of `aside` or `half` variations so they can rearrange themselves in mobile screens.

**Comment by kevinch** [comment]
Can't we achieve that with regular css on the app's side?

**Comment by kevinch** [comment]
Hmm doesn't look like we can.

**Comment by estacioneto** [comment]
Yeah... It's not something easy to achieve with regular CSS. But I think it should be something our components should handle.

**Comment by kevinch** [comment]
What if you use https://styleguide.vtex.com/#/Components/Containers/Box?

**Comment by estacioneto** [comment]
That's what I said in the description, @kevinch, the `Box` component will need this change too. In the code screenshot, you can see I had to add a `h-100` in the `styleguide__box` div.
