### ISSUE TITLE
[Menu] disable options

### ISSUE THREAD

**Issue by igorbrasileiro** [vtex/styleguide#1150]
## Purpose
Disable the Menu component options.
Tabs component use Menu to handle collapsed tabs, but some tabs can be disabled and the Menu component don't disable options.

## Context
Menu with `last 3 months` option disabled
![image](https://user-images.githubusercontent.com/15680320/78597385-d02cb200-7823-11ea-9f2d-009fe4bb04eb.png)

## Examples
Another library that implements a disabled menu option is Material UI [menus](https://material-ui.com/components/menus/#simple-menu).

**Comment by jonathasbsouza** [comment]
We could create an `isDisabled` prop, disabling click, and using the CSS tokens for _disabled_ items.

**Comment by estacioneto** [comment]
<a href="https://imgflip.com/i/40mgri"><img src="https://i.imgflip.com/40mgri.jpg" title="made at imgflip.com"/></a>

**Comment by jonathasbsouza** [comment]
Thanks @estacioneto! I'm a noob in this dev world hahaha :)

**Comment by jonathasbsouza** [comment]
I think it's clear for everybody the design solution here. I'll remove the Design Needed label and wait for someone to solve this issue.
