### ISSUE TITLE
Padding problem in RadioGroup

### ISSUE THREAD

**Issue by kevinch** [vtex/styleguide#1159]
**Describe the bug**
Padding on the last item is slightly less than it should.

![Screen Shot 2020-04-09 at 14 12 05](https://user-images.githubusercontent.com/2573602/78922040-415ea600-7a6c-11ea-8206-048544a3b5b4.png)

**To Reproduce**
https://styleguide.vtex.com/#/Components/Forms/RadioGroup

**Expected behavior**
Similar padding betwee items.

**Screenshots**
Above.

**Comment by emersonlaurentino** [comment]
@kevinch cau u fix it? if not, I will do that.
