### ISSUE TITLE
Tooltip popup hover should be possible

### ISSUE THREAD

**Issue by estacioneto** [vtex/styleguide#1181]
**Describe the "bug"**

It makes sense to our tooltip to have a possibility of text selection, for example, even when it's configuration is to be shown on hover. Now, when the cursor is inside the popup, the tooltip vanishes.

**To Reproduce**

Try to select the text inside a `hover` tooltip.

**Comment by jonathasbsouza** [comment]
I don't have the same opinion. Tooltips are short and based on where the user is pointing. I don't see the possible usage that a user can get selecting tooltip text. Do you want to able users to copy the tooltip label?

**Comment by estacioneto** [comment]
Yes. I was thinking about the ability to copy its label.
But you're right. Maybe the tooltip should not be the one to put a copyable text and should be simpler than that.

**Comment by jonathasbsouza** [comment]
@estacioneto as we came to an agreement, I'll close this issue.
