### ISSUE TITLE
Empty state

### ISSUE THREAD

**Issue by cmdalbem** [vtex/styleguide#125]
Here's the Empty State pattern we use in the Credit Control module.
(It's already implemented, so it's just a matter of extracting it :)

![image](https://user-images.githubusercontent.com/467471/40248096-28fcb07c-5aa5-11e8-99cb-77d923ac6acc.png)

What problem it solves
===
Shows _something_ instead of _nothing_.
Explains what should be in that particular space, and encourages the designer/developer to instruct the user what to do.

According to [Swetha Suresh](https://medium.com/@swethasuresh1108/the-empty-states-design-mantra-91c56eb88b3b), an Empty State:
1. Informs about the empty screen, the whats, whys, and hows
2. Prompt towards taking an action to populate the platform
3. Educates about the platform and all its features

Design decisions
===

- A muted color ~and non-primary button~ (thx @rsimoens) are used so this component has a weak prominence in the screen.
- The container borders helps show the space that would be normally filled in the screen if it wasn't "empty". This reduces cognitive load on consequent user visits.
- Although Empty States [in the wild](http://emptystat.es/) often include a personalized icon, we decided not to include it here for now. In the Credit Control case we had half a dozen empty states possible, and it would be cumbersome to search for custom icons for each one, and we couldn't come up with a reusable pattern for that. In addition to that, an icon, even if with muted colors, adds a lot of visual weight to this section, which in our case wasn't desirable.
- The rounded corners are simple decorative elements that makes this component fit better with VTEX visual patterns.

Example of application
===
![image](https://user-images.githubusercontent.com/467471/40248088-233923aa-5aa5-11e8-8968-cdddf9bbfd4c.png)

Props
===
The idea is that all fields (heading, body and call-to-action) are optional, however at least a heading or a body should be present for it to make sense.
Optionally the call-to-action can be a link, let's say to a VTEX Help article for example.

Figma link
===
https://www.figma.com/file/a94lX91ZmYGIDBxvb8shwLn8/VTEX-Design?node-id=191%3A1823

**Comment by rsimoens** [comment]
Dependendo do contexto, podem ter casos em que o CTA fique melhor em um botão primário. Deveria ser possível customizar isso no componente.

**Comment by klzns** [comment]
CTA?

**Comment by cmdalbem** [comment]
(oops, cliquei no `Close` sem querer)
