### ISSUE TITLE
InputSearch icon unaligned

### ISSUE THREAD

**Issue by TasGuerciMaia** [vtex/styleguide#1302]
**Describe the bug**

The search icon is not vertically aligned

**To Reproduce**

I verified this on an admin app and then checked on the style guide page, it is 

**Expected behavior**

The icon should be vertically centralized, even with odd numbers as margin. 

**Screenshots**

<img width="1229" alt="Screen Shot 2020-08-11 at 16 34 11" src="https://user-images.githubusercontent.com/13242383/89942760-8568df80-dbf3-11ea-9a8d-fb8b4a6d7ad5.png">

**Additional context**

**Comment by Thiago-Santos-SI** [comment]
Ola, eu resolvi esse bug, vou abrir uma PR se não tiver problema

**Comment by Thiago-Santos-SI** [comment]
hey guys, I solved this bug. I will create a PR if it's not a problem

**Comment by estacioneto** [comment]
Thank you for the contribution @Thiago-Santos-SI !

@jonathasbsouza please comment here about the alignment. It wasn't so clear because the issue says a different thing. I was a little bit confused too 😕

**Comment by jonathasbsouza** [comment]
Sorry, I didn't see this open issue before :( Maybe @TasGuerciMaia can give more context. But the tl;dr of my opinion is that in `Small` variant this difference is on purpose, to do some optical alignment.

**Comment by TasGuerciMaia** [comment]
@jonathasbsouza I disagree, here is a print without the margin markers I put before. This is an example of the small size.
<img width="393" alt="Screen Shot 2020-09-01 at 15 50 59" src="https://user-images.githubusercontent.com/13242383/91893841-1f5bff00-ec6b-11ea-8124-b06ba1d58ad3.png">

I really don't remember when this adjustment was made. But IMHO it is not an optical adjustment but a unalignment.  Mainly because the upside of the icon has more weight than the bottom side. For a successful optical adjustment the area with less visual reference should be the one that compensates and not the other way around.

**Comment by estacioneto** [comment]
So the issue and the PR still make sense... What do you think @jonathasbsouza?

**Comment by estacioneto** [comment]
Solved on #1308
