### ISSUE TITLE
AutoComplete padding-right is too big in Table V2

### ISSUE THREAD

**Issue by JuanBarros2** [vtex/styleguide#1306]
**Describe the bug**
When you have a long placehold (enough to touch the padding-right), you could see that padding-right is different than padding-left. This occurs because was sets this padding default to avoid overflow the CloseIcon.

**To Reproduce**
1. Go to AutoComplete in a TableV2 component.
2. Try to set a placeholder that overflow the input field.

**Expected behavior**
I think that is better to have a condition that changes this padding if CloseIcon is showing or not.

**Screenshots** 
![Captura de tela de 2020-08-20 14-30-30](https://user-images.githubusercontent.com/11728655/90805247-c054cc80-e2f1-11ea-9fa2-c50ccd21d4a2.png)

**Additional context**
If there's no problem, I can fix this issue :D

**Comment by estacioneto** [comment]
Nice one! I think it makes sense to not have the padding when there's no close icon. Really want to see that PR ✨
