### ISSUE TITLE
Can we have a parameter called fullHeight to render the table without know his size?

### ISSUE THREAD

**Issue by matecomp** [vtex/styleguide#1361]
As we can see at the below code, we always set the table height:
https://github.com/vtex/styleguide/blob/e597cb65dc49f31b45a471839b6f470013388f28/react/components/EXPERIMENTAL_Table/Sections/index.tsx#L35

----

In this scenário, if we don't put the table height parameter, the component will show all items:

[![Image from Gyazo](https://i.gyazo.com/a95a6ec64b3120f49037544fc194d86c.gif)](https://gyazo.com/a95a6ec64b3120f49037544fc194d86c)

Can We have a boolean parameter called fullHeight and if his value is true, we don't set the height?

```js
function Sections(
  { children, className, motion, disableScroll = false, fullHeight = false }: Props,
  ref: Ref<HTMLTableElement>
) {
  const { emptyState, empty, loading } = useLoadingContext()
  const { testId } = useTestingContext()
  const { tableHeight, bodyHeight } = useMeasuresContext()

  const sectionStyle = { ...motion }
  if (!fullHeight) {
    sectionStyle.height = tableHeight
  }

  return (
    <div
      style={sectionStyle}
```

**Comment by estacioneto** [comment]
Hello, @matecomp!

I don't see a problem with that. I think it can be added 🙂 
What do you think, @matheusps?

**Comment by matheusps** [comment]
IMO this is a bug in the behavior and not another feature that we must support. The items should always fit on the table without custom properties. Maybe we need to calculate the height correctly or/and not add it when scrolling isn't needed. 
What do you think @matecomp ?

**Comment by estacioneto** [comment]
@matheusps, I completely agree! I think @matecomp thought the same as I did:
Since we are using `height: tableHeight`, this must have been added for some purpose. Otherwise, the default would be `height: 'auto'` and the problem wouldn't exist.

I don't remember why we needed that. Do you?

**Comment by matheusps** [comment]
Honestly, I don't remember either 😅. I suppose is for scrolling, but it's been a while since I touched this component. Right now, this height feels unnecessary, because we already set each row height based on density.

**Comment by estacioneto** [comment]
Yep. I remember that it would be something related to scrolling.
@matecomp, you could test this change in [vtex/admin-inventory](https://github.com/vtex/admin-inventory), [vtex/vtexlog.admin-packing](https://github.com/vtex/vtexlog.admin-packing), and I believe in [vtex/admin-collections](https://github.com/vtex/admin-collections) too, to see if the layout won't break.

**Comment by matecomp** [comment]
Of course, I will test. Thank you guys
