### ISSUE TITLE
Modal closes and opens after an onChange occurs inside it

### ISSUE THREAD

**Issue by mathdevelop** [vtex/styleguide#1373]
**Describe the bug**
I have a <Dropdown> and an <Input> inside a Modal, when the onChange event is triggered in any of them, the component is removed from the DOM and added again.

**To Reproduce**
1. Add the component: <Modal>
2. Add any component that fires onChange inside it
3. Check the <Modal> component being removed and added from the DOM

**Expected behavior**
Modal must remain open when the open property is true.

**Screenshots**
<img width="1792" alt="modal" src="https://user-images.githubusercontent.com/17346972/111309968-42646400-863b-11eb-8ce3-78914bc2c2d2.png">

**Additional context**
Even leaving the property open={true}, a problem still occurs.

**Comment by mathdevelop** [comment]
Yes, I can, the parent component has several states being used, but I will try to abstract that out.

`
const MyComponent = () => {
  const [modalRefusal, setModalRefusal] = useState<Boolean>(false)
  const [reasonRefusal, setReasonRefusal] = useState<String>('Cliente cancelou')
  const [reasonRefusalSelected, setReasonRefusalSelected] = useState<String>('Cliente cancelou')
  const [errorReasonRefusal, setErrorReasonRefusal] = useState<String>('')
  const [savingRefusal, setSaveRefusal] = useState(false)

  const optionsRefusal = [
    {
      value: 'Cliente cancelou',
      label: 'Cliente cancelou',
    },
    {
      value: 'Falta de chopeira',
      label: 'Falta de chopeira',
    },
    {
      value: 'Região da entrega não atendida pela loja',
      label: 'Região da entrega não atendida pela loja',
    },
    {
      value: 'CEP inválido',
      label: 'CEP inválido',
    },
    {
      value: 'Sem contato com o cliente',
      label: 'Sem contato com o cliente',
    },
    {
      value: 'Outros',
      label: 'Outros',
    },
  ]

  const updateReasonRefusal = value => {
    if(value === 'Outros') {
        setReasonRefusal('')
    } else {
        setReasonRefusal(value)
    }

    setReasonRefusalSelected(value)
  }

  const handleRejectOrder = async () => {
    if(reasonRefusal === '') {
        setErrorReasonRefusal('Digite uma mensagem')

        return;
    }

    setSaveRefusal(true)

    //Business rule

    setSaveRefusal(false)
  }

  return (
    <Modal centered responsiveFullScreen isOpen={modalRefusal} onClose={() => setModalRefusal(false)}>
      <div style={{ margin: '30px 0' }}>
        <Dropdown
          label="Motivo da recusa"
          size="small"
          options={optionsRefusal}
          value={reasonRefusalSelected}
          onChange={(_: any, v: any) => updateReasonRefusal(v)}
        />
      </div>
      {reasonRefusalSelected === 'Outros' &&
          <div style={{ marginBottom: '30px' }}>
              <Input
                  placeholder="Informe o motivo da recusa"
                  size="small"
                  maxLength="50"
                  onChange={e => {
                      setReasonRefusal(e.target.value)
                      setErrorReasonRefusal('')
                  }}
                  value={reasonRefusal}
                  errorMessage={errorReasonRefusal}
              />
          </div>
      }
      <Button variation="primary" size="small" isLoading={savingRefusal} onClick={() => handleRejectOrder()}>
        REJEITAR
      </Button>
      <Button variation="secondary" size="small" onClick={() => setModalRefusal(false)}>
        CANCELAR
      </Button>
    </Modal>
  )
}
`

If you can enter my Workspace (https://orderdetails--choppbrahmaexpressmorumbi.myvtex.com/admin/orders/details/?order=SLR-1074531672178-01)

**Comment by estacioneto** [comment]
Nice! I saw that when changing the dropdown's value, this happens:

![image](https://user-images.githubusercontent.com/15948386/111327918-8f9d0180-864c-11eb-8ae0-041f547db4f4.png)

Also, maybe it's happening because you are always defining the `CancelOrder` component inside `OrderDetails` and it makes React remount the component instead of using the same component with a different state. I got your code in this comment and put it inside Styleguidist and this is the result:


https://user-images.githubusercontent.com/15948386/111330775-020ee100-864f-11eb-9708-73ead27322eb.mov

**Comment by mathdevelop** [comment]
That's right, React was rendering again the component responsible for Modal. Thank you very much for your help and sorry for any inconvenience. You can close this Issue here, see you!!
