### ISSUE TITLE
Adjust sizes of input (and possibly other controls) to match new sizing defaults

### ISSUE THREAD

**Issue by cmdalbem** [vtex/styleguide#139]
The buttons' default sizes were adjusted to be one step bigger, but other components weren't adjusted accordingly.
As an example, take this screen from Credit Control that was just updated to the latest version of the Styleguide: default buttons are now bigger, but the default input is still the same, thus ending up misaligned.

![image](https://user-images.githubusercontent.com/467471/40667399-76c8949c-6338-11e8-86c1-105cabe19d00.png)

**Comment by lbebber** [comment]
fixed by https://github.com/vtex/styleguide/pull/431, afaik

if not, reopen this issue
