### ISSUE TITLE
Dropdown onClose and onOpen not Working

### ISSUE THREAD

**Issue by victorgrodriguesm7** [vtex/styleguide#1417]
**Describe the bug**
The Dropdown has the arguments `onClose` and `onOpen`, but they're not implemented in the code.

**To Reproduce**
```tsx
import { Dropdown } from 'vtex.styleguide';

const initialValue = "visa";
const options = [
    { value: 'visa', label: 'Visa' },
    { value: 'mastercard', label: 'Mastercard' },
    { value: 'elo', label: 'Elo' },
];

export default function Component(){
    function onOpen(){
        console.log("Dropdown has been opened");
    }

    function onClose(){
        console.log("Dropdown has been closed");
    }

    return (
        <Dropdown
            value={initialValue}
            options={options}
            onClose={onClose}
            onOpen={onOpen}/>
    )
}
```

**Expected behavior**
The callback `onOpen` and `onClose` should be called when the Dropdown is opened or closed

**Comment by estacioneto** [comment]
Hi @victorgrodriguesm7! Thank you for submitting this issue!

Since these functions don't work for now and we already have both `onFocus` and `onBlur` functions, we might delete the `onOpen` and `onClose`.

Would you like to make this change?

**Comment by victorgrodriguesm7** [comment]
Yeah, sure. I'll fork the repo and start to working on this.

**Comment by victorgrodriguesm7** [comment]
I opened the PR on  #1418 .

**Comment by estacioneto** [comment]
The changes were published and deployed. Thanks again, @victorgrodriguesm7!
