### ISSUE TITLE
Input and Textarea inline edit

### ISSUE THREAD

**Issue by cmdalbem** [vtex/styleguide#143]
Here are the components we created for Credit Control to edit fields "inline".
(It's already implemented, so it's just a matter of extracting it :)

![image](https://user-images.githubusercontent.com/467471/40806974-6df75b06-64f9-11e8-8ff4-71e552ad0e79.png)

What problem it solves
===
Provides a simple interaction pattern to do small edits in place of fields that start as "read-only".
You might need this if you have a very long form and want to provide users the possibility of editing just small parts of it, without having to resubmit everything.
Or you just have a screen with lots of information and just some of them are editable.

Design decisions
===

- the `edit` button has very low prominence because it should be used in places where the main user drive is not to edit information or input new one.
- the `update` button starts disabled, and becomes enabled if the original information is indeed edited
- originally the cancel button in the Regular input variation had a `cancel` label, but it was taking too much space in our UI so we made it a _little_ less intuitive and converted it to be a `✕`

Examples of application
===

![image](https://user-images.githubusercontent.com/467471/40806284-62eb82d4-64f7-11e8-8acd-ae8b3473470a.png)

![image](https://user-images.githubusercontent.com/467471/40806355-954729c2-64f7-11e8-9284-74f133c6b505.png)

![image](https://user-images.githubusercontent.com/467471/40806384-b0620ec0-64f7-11e8-8ec9-33bf28412673.png)

Figma link
===
https://www.figma.com/file/a94lX91ZmYGIDBxvb8shwLn8/VTEX-Design?node-id=2596%3A1

**Comment by fredppm** [comment]
@cmdalbem, why sometimes the cancel is an icon X and other times, is a button?
It comes to my mind in the ref #218 discussion

**Comment by kevinch** [comment]
@emersonlaurentino check with the design team before coding anything. This is an old issue and the solution displayed above might not be up to date.

**Comment by emersonlaurentino** [comment]
@kevinch yes, I spoke to @rsimoens and he's about to close this issue. But I will close and then he explains why.
