### ISSUE TITLE
Simple page header

### ISSUE THREAD

**Issue by cmdalbem** [vtex/styleguide#145]
Here's a proposition of generic, simple page header to use in our admins.
(it's already implemented in Credit Control, so it's just a matter of extracting it :)

![image](https://user-images.githubusercontent.com/467471/40809792-11788a22-6502-11e8-9dc6-1016b44bde80.png)

What problem it solves
===
Our new admin sidebar provides a global solution for 1st-level navigation (between modules) and 2nd-level navigation (sections inside a module), but 3rd-level navigation is left for each module team to handle.
To improve consistency in the platform I propose this generic solution for handling simple 3rd-level navigation needs.

Design decisions
===

In the old Admin we used to deal with this with breadcrumbs, which might end up encouraging designers to create profound information architectures.
In the spirit of the Simplicity Principle, this solution encourages modules to not going much deeper in the navigation given it doesn't provide a breadcrumb or tabs, but a simple `back` link in the top.

It's important that in the implementation the vertical space for the back link is left blank if the link is not available. In other words, the main heading should always have the top margin in relation to the module available viewport. 

Examples of application
===

![image](https://user-images.githubusercontent.com/467471/40810131-3cb78548-6503-11e8-94fa-6130e5935d68.png)

![image](https://user-images.githubusercontent.com/467471/40810134-43ff51f0-6503-11e8-8a65-1be74107fd5b.png)

Figma link
===
https://www.figma.com/file/a94lX91ZmYGIDBxvb8shwLn8/VTEX-Design?node-id=191%3A1152

**Comment by kevinch** [comment]
Done.
