### ISSUE TITLE
Update icon import example

### ISSUE THREAD

**Issue by lbebber** [vtex/styleguide#152]
Right now, the example of importing icons is as follows:

```
const ArrowBack = require('./ArrowBack').default
const ArrowDown = require('./ArrowDown').default
const ArrowUp = require('./ArrowUp').default
...
```

It's not clear what is the right way to import icons on projects

**Comment by klzns** [comment]
That's the only way to make the example code to work. We can't change that.

We could display something like this to solve this issue:
![image](https://user-images.githubusercontent.com/284515/40992516-6b0c7d40-68cd-11e8-87e1-69287eafe3b5.png)

**Comment by lbebber** [comment]
Sounds good enough to me
