### ISSUE TITLE
Typography classes with set line-heights and letter-spacings

### ISSUE THREAD

**Issue by alinevillaca** [vtex/styleguide#155]

**Comment by alinevillaca** [comment]
![fabriga settings](https://user-images.githubusercontent.com/15332517/41165167-580efca2-6b13-11e8-8b88-c0a436659196.jpg)

**Comment by davicosta99** [comment]
@alinevillaca Shouldn't this issue be in Tachyons instead? Line-heights and letter-spacings are defined there.

https://github.com/vtex/vtex-tachyons/

**Comment by cmdalbem** [comment]
@ntmedina @alinevillaca do you have updates or could give more details about this please?
