### ISSUE TITLE
Create RadioGroup/OptionGroup component

### ISSUE THREAD

**Issue by lbebber** [vtex/styleguide#161]
Need some input here to see whether this (components that are groups of radio buttons) should be created at all or not, and if so, which would be the best name and API for it, as well as some design considerations

In my opinion, it should be created, as:
- it's a common use case (you pretty much never have a single option)
- makes it easier to use; with multiple options, you have to juggle different `id`s, `key`s, multiple `checked` checks, etc. Besides being a bit of a pain, this also might be a point of failure, with people forgetting to add `keys`, mixing up `id` and `name`, and whatnot.

**Comment by klzns** [comment]
Check this tweet when designing its API:
https://twitter.com/ryanflorence/status/999082532753702912?s=09

**Comment by cmdalbem** [comment]
Implemented by https://github.com/vtex/styleguide/pull/171
