### ISSUE TITLE
a11y Radio Buttons

### ISSUE THREAD

**Issue by lbebber** [vtex/styleguide#170]
Right now it doesn't seem to be possible to even tab your way into radio buttons.

**Comment by kevinch** [comment]
It is via the arrow keys. Tab will focus (without visual clue though) the radio group.

**Comment by emersonlaurentino** [comment]
The behavior of using the arrows is correct, however it has no indicator of which Radio is selected.

I created an issue to solve accessibility issues in the components, so I'll close this issue to discuss in issue #850
