### ISSUE TITLE
Use currentColor as the default icon color

### ISSUE THREAD

**Issue by lbebber** [vtex/styleguide#182]
This allows for more consistent and predictable coloring of icons, perhaps eliminating the need of manually setting icon colors altogether.

**Comment by cmdalbem** [comment]
Acho ótimo isso, acho que faz bastante sentido do ponto de vista de design também, porque raramente um ícone vai ter cor diferente do que um texto teria no lugar.

**Comment by lbebber** [comment]
Fixed long ago by https://github.com/vtex/styleguide/pull/190
