### ISSUE TITLE
Allow button with spinner to keep both label and spinner at the same time

### ISSUE THREAD

**Issue by lbebber** [vtex/styleguide#185]
Doing so prevents from losing context of what the button does and what the user is waiting for. It also allows for buttons to have a loading state that is not result of direct action with it, but which prevents or delays the action that the button does.

Some care would need to be taken with not stretching the button, or if so, how it would be done.

**Comment by cmdalbem** [comment]
@lbebber será que tu tinha em mente algum exemplo de alguém que faça isso?
Assim de cabeça eu só consigo pensar em casos onde o label some pra dar espaço ao spinner - que é algo que não vejo problema, dado que provavelmente o usuário que clicou na ação então ele sabe o que tinha ali e o que ele está esperando.
Mas percebo que teu ponto aqui é pro caso de carregamento causado por algo externo ao clique naquele botão. Será que tu consegue me explicar em mais detalhes esse contexto? Posso te ajudar a pensar em alguma outra solução pra isso, que não precise dessa alteração do comportamento dos botões com spinner.

**Comment by cmdalbem** [comment]
@lbebber up

**Comment by lbebber** [comment]
@cmdalbem eu pensei melhor, e acho que tem jeito melhor de solucionar o segundo caso.

(a ideia é, nao precisa aparecer spinner, e se o cara por acaso clicar enquanto tem que esperar alguma request terminar, aí sim aparece o spinner normalmente)

mas eu ainda acho positivo poder manter o texto do que o botao ta fazendo (e.g. "Enviar"/"Enviando..."). só nao sei se vale o esforço pensar nisso agora

**Comment by emersonlaurentino** [comment]
@lbebber @cmdalbem atualmente nosso botão em estado de loading adiciona um spinner e substitui o texto. Ainda iremos colocar que o spinner ao lado do texto?

_Esta issue ainda deveria está aberta?_

**Comment by jonathasbsouza** [comment]
As anyone has been active in this conversation, I will close this issue.
