### ISSUE TITLE
Create bg-dim color

### ISSUE THREAD

**Issue by lbebber** [vtex/styleguide#186]
Used for the overlay on modal windows, etc. Should have the alpha channel embedded—i.e., it should be `rgba`.

**Comment by klzns** [comment]
No Bootstrap nao é rgba. Olha como eles fazem:


 
![image](https://user-images.githubusercontent.com/284515/41972716-0b34f758-79e9-11e8-85e3-2a0c7ab520c5.png)

**Comment by klzns** [comment]
O nome backdrop também é interessante.

**Comment by kevinch** [comment]
@klzns chegou a criar esse token?

**Comment by kevinch** [comment]
Closing since we implemented `react-responsive-modal` with inline styles for the modal/dialog:
```
styles={{
          overlay: {
            backgroundColor: 'rgba(0, 0, 0, 0.8)',
```

**Comment by emersonlaurentino** [comment]
@thayannevls can u fix this issue in new modal?

**Comment by thayannevls** [comment]
Sorry, I didn't understand very well the issue. Currently, in the new Modal we are using the tachyons token `bg-black-70` which controls the opacity and color

**Comment by emersonlaurentino** [comment]
@lbebber the idea this PR is to create a design token in tachyons to a mask, example of use: background overlay of modal?

**Comment by jonathasbsouza** [comment]
I would change this issue's perspective a little bit:

1) choose a vtex-tachyons color [Base, #3F3F40] to be the modal-backdrop-color;
2) define a modal-backdrop-opacity in tachyons
3) change the `react-responsive-modal` custom css.

I think it's a good first issue. @thayannevls do you know anybody that could do it?
