### ISSUE TITLE
Create Spinner/Stepper/Number Input

### ISSUE THREAD

**Issue by lbebber** [vtex/styleguide#193]
_Name to be defined; they all seem to be ambiguous._

Overview
===

This is a special case of a Numerical Input, where you expect the user to modify it by a few incremental steps.

Purpose
===

_Which problems were you trying to solve when you came up with this? What use cases does it cover that other components don't? Don't hesitate to mention other existing similar components and why they don't work for you._

Design decisions
===

_Try to justify each and every decision you took while designing this component. Why did it end up looking and behaving this way, and not somehow else?
This section is very important for the design process, but it doesn't need be part of the final documentation._

Examples
===

_Show where you're already using it or where you envision it being used. Don't worry about cropping your screenshot, it's good if you capture the full context of your application._

Figma link
===
https://www.figma.com/file/a94lX91ZmYGIDBxvb8shwLn8/VTEX-Styleguide?node-id=148%3A969

**Comment by cmdalbem** [comment]
Posso te ajudar a desenhá-lo! Pode me explicar em mais detalhes o caso de uso? Prevê um contexto já em que ele vai ser usado? Uma tela, um módulo?

**Comment by lbebber** [comment]
@cmdalbem Atualmente pra mim, páginas de produto e carrinho do inStore, pra alterar quantidade de um produto. Na página de produto ele deve ficar maior do que no carrinho. Eventualmente num futuro distante o checkout tambem usaria isso, pra mesma finalidade.

O Pages tambem tem uns casos de uso, pra editar certos tipos de quantidade num componente (por exemplo, items num carousel).

Se quiser, podemos conversar

**Comment by cmdalbem** [comment]
Desenhei algumas opções para debatermos:

![image](https://user-images.githubusercontent.com/467471/42290246-6f0dbde4-7f9a-11e8-8394-3ac0d7c2c034.png)

**Comment by cmdalbem** [comment]
No contexto do InStore:

![image](https://user-images.githubusercontent.com/467471/42290442-98eb6d04-7f9b-11e8-8109-ca334820075d.png)

(figma: https://www.figma.com/file/NWJ9aStICOMgCBovveArYTJ1/Documentac%CC%A7a%CC%83o_Edic%CC%A7a%CC%83o_inline)

**Comment by lbebber** [comment]
Só pra deixar registrado a conversa: Eu prefiro, nesse exemplo do inStore, o primeiro.

O segundo não é ruim, mas talvez chame atenção demais pra uma ação que praticamente nunca é primaria, ainda mais quando for uma lista com varios produtos. 

O terceiro não é horrivel, mas o tom do azulzinho é muito próximo do tom de cinza da borda no nosso tema de cor e conflita com ele, e em outros temas a cor secundária pode ser vibrante e causar o mesmo problema de chamar atenção demais.

No primeiro, os botões já seguem um padrão de ação estabelecido pelo button tertiary, e ficam bem em uma lista. Não vejo caso em que esses botões tenham ação primária—eles são equivalentes a um Input.

**Comment by cmdalbem** [comment]
Por mim pode implementar esse que gostamos mais então! Vou marcar aqui como Design Done, qualquer coisa iteramos em cima disso se tiver mais feedbacks :)
