### ISSUE TITLE
[Button variation="tertiary"] Allow for negative margins to cancel out paddings

### ISSUE THREAD

**Issue by lbebber** [vtex/styleguide#194]
...so we can prevent this kind of issue:

<img width="587" alt="screen shot 2018-06-28 at 15 29 15" src="https://user-images.githubusercontent.com/5691711/42113450-ae114768-7bc1-11e8-9b3c-f79a9522e86f.png">

The question lies in how would this be done—through specific props for which margin will be negative?

**Comment by kevinch** [comment]
@cmdalbem isso é uma coisa que foi confirmada do lado de vcs?

**Comment by cmdalbem** [comment]
@kevinch não lembro se foi discutido em grupo, mas lembro de ter discutido com algumas pessoas já, incluindo o Bebber, e lembro de sempre termos chegado à conclusão de que era algo que fazia sentido! 👍 
Concordamos também que parece fazer sentido isso ser tratado internamente pelo proprio componente de Button. Ele ganharia uma prop que faria ele aplicar em si mesmo as margens negativas correspondentes ao seu padding.
