### ISSUE TITLE
Add support for icons or whatever on Input's prefix prop

### ISSUE THREAD

**Issue by lbebber** [vtex/styleguide#196]
For use cases like this one:
<img width="354" alt="screen shot 2018-07-03 at 19 26 06" src="https://user-images.githubusercontent.com/5691711/42247391-0ebef50a-7ef7-11e8-8886-50be7d7f9f83.png">

Another example following the one given on the styleguide page, currencies that don't necessarily have characters for them (such as cryptocurrencies).

Perhaps this is just a matter of the `prefix` prop supporting the `node` proptype instead of just `string`, but a `icon` prop might be preferable. Up to discussion.

**Comment by lbebber** [comment]
Related to https://github.com/vtex/styleguide/issues/144

**Comment by cmdalbem** [comment]
@lbebber temos agora a opção de `suffixIcon`, que acho que é basicamente a mesma coisa que tu tinha proposto aqui mas com a opção de ser prefixo _ou_ sufixo, né?

**Comment by cmdalbem** [comment]
@lbebber up

**Comment by lbebber** [comment]
@cmdalbem exatamente

**Comment by lbebber** [comment]
@cmdalbem nao sei qual API seria melhor, um `icon` + `iconPosition` (ou similar), ou `suffixIcon` e `prefixIcon`. ou só `suffix` e `prefix` e tu pode passar tanto texto como um icone.

**Comment by cmdalbem** [comment]
Não consigo imaginar um caso que faça sentido ter prefixo E sufixo, e provavelmente ficaria estranho. Pare legal essa ideia de uma prop que tu passa texto/ícone e se é sufixo/prefixo.
Eu faria um benchmarkzinho pra ver como outros styleguides mais maduros tratam isso.

**Comment by lbebber** [comment]
@cmdalbem nao é pra ter ambos ao mesmo tempo, mas é uma questao de deixar a API mais simples.

tu passar só `<Input prefix="x" />` ou `<Input suffix="x" />` é mais simples e direto ao ponto do que ter uma prop pro simbolo e uma pra posiçao

**Comment by lbebber** [comment]
se o usuario passar os dois, poderia disparar um warning
