### ISSUE TITLE
Create template for pull requests

### ISSUE THREAD

**Issue by lbebber** [vtex/styleguide#197]
https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/

Specifically, it should remind that pretty much all PRs must be accompanied by updates on the changelog.

Of course other tips or rules might be included, this is open to discussion.

**Comment by kevinch** [comment]
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have updated the `changelog.md` file
- [ ] I have updated the version number in the `package.md` file
- [ ] I have created and pushed the corresponding tag version
- [ ] I have updated the snapshots

**Comment by klzns** [comment]
```diff
- changelog.md
+ CHANGELOG.md

- package.md
+ package.json
```

Faltou colocar mudar a versao do `manifest.json`

**Comment by klzns** [comment]
E eu nao sei se curto mt os checkboxes pq o Github renderiza uma progress bar na listagem de PRs e Issues.

**Comment by lbebber** [comment]
@klzns Eu tb acho meio chato isso, mas não sei de alternativa melhor.

**Comment by lbebber** [comment]
Talvez o type of change seja melhor nao ser checkbox, mas o checklist acho legal.

**Comment by salesfelipe** [comment]
Resolvido
