### ISSUE TITLE
Input with mask

### ISSUE THREAD

**Issue by fredppm** [vtex/styleguide#210]
## Overview

An input with a mask 

## Purpose 

Force the user to use a correct input value before the validation

## Example

Card number
Phone number
Postal code number

(Sorry no images)

**Comment by hapoza** [comment]
+1 to this issue!

My use case is formatting/masking phone numbers using a template passed as props, to make it more dynamic and useful to many countries.
I've found the same functionality on `@vtex/address-form/lib/inputs/StyleguideInput`, that seems to be just a wrapper around `vtex.styleguide/Input` who adds more functionality. I could try to use it directly, but that project is not open source and not documented as well.
My proposal is to migrate that code into styleguide and add it to the docs, or adding a similar functionality to the Input.

**Comment by kevinch** [comment]
@klzns @fredppm @hapoza closing this issue.
