### ISSUE TITLE
Header with buttons

### ISSUE THREAD

**Issue by fredppm** [vtex/styleguide#211]
Use the right side to place some buttons there.

Eg
![image](https://user-images.githubusercontent.com/12805319/42541416-9cbf7dc6-8478-11e8-9fa8-267ca3a59c06.png)

**Comment by kevinch** [comment]
@cmdalbem isso me parece uma coisa que deveria entrar no conteúdo da página mesmo e não no Pageheader. Que acha?

**Comment by cmdalbem** [comment]
@kevinch @fredppm pois é, não ficou super claro pra mim a necessidade de incluir isso junto no header, se facilmente pode ser adicionado logo abaixo. Pra tornar isso uma opção do header teria que ter mais claro que isso fosse uma necessidade de vários contextos diferentes, pra ter certeza que isso vai fazer sentido quando a galera sair usando.
@fredppm qual tua ideia de aplicação disso?

**Comment by fredppm** [comment]
Era evitar o consumo de espaço vazio,. Esse header é monstruoso no meu laptop, chega a ser 20% da minha navegação. Todo o espaço lateral fica sem utilização, ao colocar os botões em uma linha a baixo eu "Fred Mourão" sou obrigado scrollar mais ainda para ver os primeiros dados da tela.

Aproveitando
![image](https://user-images.githubusercontent.com/12805319/43231125-683092f0-9041-11e8-9bbb-c55901e76413.png)


Nova linha
![image](https://user-images.githubusercontent.com/12805319/43231173-a3d37c78-9041-11e8-91ef-6f74f7362d01.png)

**Comment by cmdalbem** [comment]
@gabrielgalc tenho a impressão que vi uma tela tua esses dias que fazia algo nesse estilo, confere?

**Comment by cmdalbem** [comment]
@fredppm muito obrigado pelas screenshots, acho que tá bem claro que não tá legal isso aí mesmo.

**Comment by cmdalbem** [comment]
@fredppm estamos conversando sobre tua sugestão aqui, ela é bem boa e acho que vai pra frente. Mas independente da decisão de permitir ou não botões, reparamos que o PageHeader da tua screeshot não parece estar igual ao atual do Styleguide.
Tu tá usando o componente do Styleguide, ou tu recriou ele? Tu tá usando a última versão do Styleguide?

**Comment by fredppm** [comment]
@cmdalbem não esta usando não, é um fake meu, o atual não permite botões sobre ele. (poderia solucionar com absoluto e viver com alguns cálculos de resolução, mas é a uma solução porca)

**Comment by gabrielgalc** [comment]
@cmdalbem , acho que no collection ou no pages admin, mas como definimos os headers funciona para os dois casos

**Comment by alinevillaca** [comment]
Design done para primeiro e segundo nível sem tabs (teu cenário, @fredppm ): https://www.figma.com/file/a94lX91ZmYGIDBxvb8shwLn8/VTEX-Styleguide?node-id=0%3A1

Em breve vou escrever as guidelines de uso, porque fica um pouco mais complexo que usa-se tabs.

![image](https://user-images.githubusercontent.com/15332517/43658112-47ed4ad0-972e-11e8-9302-e507bb6b0781.png)

**Comment by cmdalbem** [comment]
implemented by https://github.com/vtex/styleguide/pull/263
