### ISSUE TITLE
List menu

### ISSUE THREAD

**Issue by fredppm** [vtex/styleguide#212]
A menu that can be used with context or ellipses button.

Sample:
https://www.npmjs.com/package/react-menu-list

**Comment by cmdalbem** [comment]
Mais exemplos:

https://polaris.shopify.com/components/actions/action-list
https://atlassian.design/guidelines/product/components/drop-menu

**Comment by lbebber** [comment]
Já fiz um componente parecido pro instore, posso implementar isso quando tiver o design. Topa @cmdalbem?

**Comment by cmdalbem** [comment]
@lbebber bóra!

**Comment by kevinch** [comment]
Closing since https://github.com/vtex/styleguide/pull/426 has been merged. Ex: https://styleguide.vtex.com/#/Components/Forms/ActionMenu
