### ISSUE TITLE
Field set or Grouping fields

### ISSUE THREAD

**Issue by fredppm** [vtex/styleguide#214]
## Overview

Field set isn't more a common approach but sometimes is to detach a group of fields from others.

## Propuse 

Group fields in a context with possibles to edit all fields.

## Examples

![image](https://user-images.githubusercontent.com/12805319/42572264-b3cb6f76-84ef-11e8-980e-ea9c6c021ba2.png)

**Comment by cmdalbem** [comment]
@fredppm o foco da demanda aqui seria pra criar um tipo de "template" que facilite a edição de todos inputs de uma vez só, né? Porque imagino que se fosse só pra agrupar visualmente os inputs um pouquinho de HTML já resolveria, né?

**Comment by emersonlaurentino** [comment]
@cmdalbem esta issue ainda deveria está aberta?

**Comment by jonathasbsouza** [comment]
As anyone has been active in this conversation, I'll close this issue.
