### ISSUE TITLE
Scroll bar

### ISSUE THREAD

**Issue by fredppm** [vtex/styleguide#216]
## Overview

Transform the same scrollbar used in the menu to component 

## Purpose 

Transform an already developed element to Style Guide integrate component 

## Examples

This is not an exactly sample, this is already real using of the element
![image](https://user-images.githubusercontent.com/12805319/42696995-3b10c6ba-8690-11e8-82bd-54840d7d2f21.png)

**Comment by cmdalbem** [comment]
Can you comment more on that? I don't think I got what you meant.

**Comment by cmdalbem** [comment]
@fredppm ah, agora entendi! Mas será que uma scrollbar deveria ser um componente? Isso não é mais uma estilização, que deveria ser feita de maneira global?

**Comment by cmdalbem** [comment]
@fredppm depende de JS pra customizar a scrollbar? Acho que não, acho que só com CSS já resolve: https://css-tricks.com/almanac/properties/s/scrollbar/

**Comment by fredppm** [comment]
São duas coisas, se vc quer mudar o scroll bar apena é um conjunto de CSS para ser aplicado. 
Se vc qure fazer com suavidade igual ao menu, tem que aplicar um JS.

**Comment by fredppm** [comment]
@cmdalbem realmente esse componente não é JS e sim um alteração no CSS.
é questão de transformar essa issu em estilo e não componente

**Comment by cmdalbem** [comment]
Legal, verdade. Acho que isso é bem frufru, não me preocuparia com isso agora, mas se alguém quiser pegar pra fazer bóra :)
