### ISSUE TITLE
Fixed Width Icons

### ISSUE THREAD

**Issue by fredppm** [vtex/styleguide#217]
## Overview

A class or property in icons to fixed the width icons like font awesome

## Purpose

Every icon has his own width when you are writing a table design and there are different icons in each line the width will be different too. This break the symmetric.

Unsymmetric list:
![image](https://user-images.githubusercontent.com/12805319/42697246-f4d278aa-8690-11e8-9345-8a3715e69cf8.png)

## Examples

https://fontawesome.com/v4.7.0/examples/?#fixed-width

**Comment by ohmyguigs** [comment]
This will be addressed in the new icons refactor being planned here: vtex/styleguide/issues/931
