### ISSUE TITLE
Button icon with especial size

### ISSUE THREAD

**Issue by fredppm** [vtex/styleguide#218]
I really understand the current sizes of buttons but when you are using a clear button with icon the still big increasing the vertical margin,  like the sample bellow. 
Maybe the solutions is not resize the button...

![image](https://user-images.githubusercontent.com/12805319/42573226-dffba596-84f1-11e8-9d89-c7477fee4b30.png)

Debugging grid
![image](https://user-images.githubusercontent.com/12805319/42573462-872ff0b0-84f2-11e8-812f-bd63d609a3de.png)

**Comment by cmdalbem** [comment]
There's an `icon` prop that makes the button a little smaller and more squared.
But even combining this with the `small` button size I think I agree with you it's way too big:

![image](https://user-images.githubusercontent.com/467471/42652632-62868ede-85e9-11e8-8d07-0fb35fa10b9d.png)

HOWEVER there's a project of [Inline Edit component](https://github.com/vtex/styleguide/issues/143) where we solved this a little differently. We tried to avoid using just the pencil icon to be more intuitive. The button is still a little big, but as you can see it has the same height as the text input, which prevents it pushing the content down when the entering the "edit mode":

![image](https://user-images.githubusercontent.com/467471/42652752-bd487f3a-85e9-11e8-8f75-5174b3e328b0.png)

What do you think?

**Comment by fredppm** [comment]
I agree with the inline solution.
But what happened in this my example. Is not real inline, it is a form group that must have all element edit at the same time.

**Comment by kevinch** [comment]
Closing since buttons have been recently updated with icons: https://styleguide.vtex.com/#/Components/Forms?id=buttonwithicon.
