### ISSUE TITLE
Remove input placeholders

### ISSUE THREAD

**Issue by cmdalbem** [vtex/styleguide#230]
Following a recent discussion in our channel and some insightful articles on the web, placeholders have been noted as bad for the User Experience so we should discourage its use by removing it from our Styleguide.

Read more:
https://www.smashingmagazine.com/2018/06/placeholder-attribute/
https://www.nngroup.com/articles/form-design-placeholders/

**Comment by lbebber** [comment]
Discouraging is one thing; this is eliminating its use altogether.

I'm for adding warnings, but removing it seems a bit precipitate. There are at least a couple of valid use cases that we know of, and there might be more that we don't know.

**Comment by cmdalbem** [comment]
@lbebber :
From the standpoint of a new-born Design System, it seems to be a better approach to remove capabilities in the beginning and let latent needs to dictate when something should be added. Otherwise if we allow anything to be done from the beginning we'll never know if something could've been done in a different way with a little more though.
Bottom line is: when in doubt, we eliminate it.

What do you think about this philosophy?

**Comment by lbebber** [comment]
@cmdalbem Makes sense. I guess my disagreement is about the removal itself, then.

**Comment by cmdalbem** [comment]
We decided in a Styleguide meeting that we'll be just discouraging its use by documenting about it in the guidelines, and not removing it altogether.
