### ISSUE TITLE
Não é possível adicionar ícones no dropdown

### ISSUE THREAD

**Issue by analuizamtg** [vtex/styleguide#233]
Caso de uso:
![image](https://user-images.githubusercontent.com/5035494/42818350-04e3404e-89a7-11e8-9845-b491f25f68e8.png)

**Comment by cmdalbem** [comment]
@analuizamtg tu precisaria desse ícone só no botão que aciona o dropdown (como o da screenshot), ou nas opções internas dele também?

**Comment by analuizamtg** [comment]
@cmdalbem na real não sei! Foi aline que fez o design. Sabe dizer @alinevillaca ?

**Comment by alinevillaca** [comment]
Nas opções internas também! Já que o cartão é mascarado, a bandeira é mais um apoio de identificação

**Comment by cmdalbem** [comment]
Nosso dropdown hoje usa o <select> nativo do browser, que não tem suporte pra adicionar ícones nem nada visual nas opções internas.
@analuizamtg  Não vejo problemas em adicionar suporte à ícone no seletor externo (como o da screenshot), mas nas opções internas infelizmente não vai ter como enquanto não reimplementarmos do zero o dropdown (o que não vejo acontecendo tão cedo). Tu acha que essa solução parcial te ajuda?

**Comment by cmdalbem** [comment]
@analuizamtg posso fechar essa Issue?

**Comment by jullyanav** [comment]
Tenho duas observações a fazer:

1. Tive de fazer um dropdown não-nativo para o Multi-Select. Acho que podemos reaproveitá-lo para o nosso dropdown, deixando ele mais alinhado com o resto dos componentes e permitindo que essa feature seja desenvolvida;

2. Também estou precisando de algo assim. Contexto: no Rates and Benefits, existem três tipos de benefícios: brinde, preço e frete. Durante a edição de uma campanha, o usuário pode associá-la a benefícios criados anteriormente. Eu pensei em mostrar no seletor um ícone ilustrativo do tipo de benefício, para ajudar o cliente a associar rapidamente as opções:

![benefits](https://user-images.githubusercontent.com/39499441/45566166-3b6ef780-b82c-11e8-8e0a-142e3d15ac3b.png)

Para poder fazer algo assim, precisaria implementar ícones opcionais no Multi-Select. Se formos reaproveitar o que for feito lá no Dropdown, podemos ter ícones em ambos. :slightly_smiling_face:

**Comment by kevinch** [comment]
@jullyanav vc está caminhando com isso?

**Comment by jullyanav** [comment]
Não, porque por enquanto o dropdown do multiselect não está bom o suficiente pra ser replicado no nosso componente dropdown.

**Comment by cmdalbem** [comment]
@alinevillaca achei essa issue aqui antiga pra caramba, e a maioria das pessoas envolvidas nem trabalham mais na VTEX hahah Vcs ainda têm essa demanda, ou posso fechar a issue?

**Comment by klzns** [comment]
@cmdalbem eu tenho!

**Comment by klzns** [comment]
Mas nao tem como pq o select é nativo. Vou fechar a issue.
