### ISSUE TITLE
Fix Alerts layout

### ISSUE THREAD

**Issue by cmdalbem** [vtex/styleguide#246]
Our implemented Alerts are slightly off. The close icon is too small, and the icon isn't aligned with the text.

Current implementation
===
![image](https://user-images.githubusercontent.com/467471/43402042-11fbf050-93e8-11e8-822c-05ff86bcc8cf.png)

Figma version
===
![image](https://user-images.githubusercontent.com/467471/43402065-2074cc06-93e8-11e8-9134-c46a233d8e67.png)

Link do Figma
===
https://www.figma.com/file/a94lX91ZmYGIDBxvb8shwLn8/VTEX-Styleguide?node-id=148%3A967

**Comment by amandaespinosa** [comment]
O alerts que já está implementado deve ser reiterado para seguir as novas premissas.

Sobre comportamento Overlay:
The alert cannot have an "overlay" behavior. It may cover important information in contextual scenarios.

**Comment by akaFTS** [comment]
Halting development, branch name is `fix/alerts-layout` if somebody wants to take over.
