### ISSUE TITLE
Adicionar classe CSS como hook a todos os icones

### ISSUE THREAD

**Issue by klzns** [vtex/styleguide#247]
Não é possível target um icone do styleguide com CSS.

Os componentes de icones devem ter uma classe como `vtex__icon vtex__icon--plus`, para que seja possivel do lojista customizar esse elemento.

**Comment by lbebber** [comment]
Talvez usar `icon-plus` ao invés de `--plus`, e deixar o `--` pra `--outline` e talvez eventualmente outras variações.
