### ISSUE TITLE
Alert close button click area is too small

### ISSUE THREAD

**Issue by lbebber** [vtex/styleguide#269]
As the title says.

To fix this, increase its padding and add negative margins.

**Comment by akaFTS** [comment]
This is (probably) addressed in #246 since the "X" will become bigger

**Comment by cmdalbem** [comment]
duplicate of https://github.com/vtex/styleguide/issues/246

**Comment by lbebber** [comment]
@akaFTS @cmdalbem Show, só lembrar de fazer isso do padding/margem negativa, só aumentar o icone em si não é o suficiente
