### ISSUE TITLE
Refactor RadioGroup and Radio components

### ISSUE THREAD

**Issue by cmdalbem** [vtex/styleguide#274]
Here are some ideas of improvements me and @lbebber quickly discussed today:

- [x] Highlight the RadioGroup as the suggested way to use Radios (maybe even hide the documentation of the single Radio button?)
- [ ] Add helper text as a prop in the Radio component (and not a possible customization of the RadioGroup)
- [ ] Make the RadioGroup outer border _opt-in_ (optional, and off by default)

**Comment by ericreis** [comment]
@cmdalbem @lbebber could you explain a little bit more about the 2nd item (helper text)? Why are we adding a prop to the Radio component if we don't want users to use the Radio component by itself but the whole RadioGroup component?

**Comment by cmdalbem** [comment]
I think we can't safely assume nobody will ever use the Radio component on its own, for complex UI cases where the RadioGroup doesn't work. The helper text is clearly an option of the athom (Radio) and not of the molecule (RadioGroup), thus should be moved.

**Comment by emersonlaurentino** [comment]
There is currently a `hideBorder` prop in RadioGroup that hides its boders. About the help text, this discussion is being done at #936.
I am closing this issue in order to center this discussion only on issue # 936

**Comment by emersonlaurentino** [comment]
There is currently a `hideBorder` prop in RadioGroup that hides its boders. About the help text, this discussion is being done at #936.

I am closing this issue in order to center this discussion only on issue #936
