### ISSUE TITLE
Button with icon & label

### ISSUE THREAD

**Issue by kevinch** [vtex/styleguide#278]
Prepare the button to receive an icon name with a label and deal with the layout.

**Comment by kevinch** [comment]
Fix as well the Button's height when an icon is added:
![screen shot 2018-08-20 at 11 58 10](https://user-images.githubusercontent.com/2573602/44348319-7588eb80-a470-11e8-81eb-2953d6e2554d.png)

**Comment by cmdalbem** [comment]
@kevinch would this be a duplicate of https://github.com/vtex/styleguide/issues/354?
