### ISSUE TITLE
Button spinner has wrong colors

### ISSUE THREAD

**Issue by akaFTS** [vtex/styleguide#304]
The last spinner update broke the spinners used inside buttons: 

<img width="444" alt="captura de tela 2018-08-23 as 11 43 52" src="https://user-images.githubusercontent.com/6173351/44532599-d7905d80-a6c9-11e8-8fdf-4548798534c4.png">

**Comment by akaFTS** [comment]
Waiting decision on spinner colors.

**Comment by cmdalbem** [comment]
I'd say we use a neutral color, such as black or gray. Blue is our action color, whereas the spinner is the opposite.

**Comment by lbebber** [comment]
the colors are more of a "rule of thumb" thing rather than strict rules—checkboxes are clickable and are gray, as are radio buttons, tabs, and a couple of others. 

not that i'm all against the spinner being blue, but i don't think that should be the only reasoning.

**Comment by lbebber** [comment]
@cmdalbem as for the relationship between "action" and the spinner, the spinner conveys an _action in progress_.

**Comment by cmdalbem** [comment]
@lbebber I don't think it's a problem to have interactive elements that AREN'T blue. A toolbar full of buttons with icons might look overwhelming if it's all made of blue icons. But I don't like the idea of having blue things that AREN'T interactive.
--
A spinner does convey an "action in progress", but also the absence of interactivity. A spinner says "hold on, I'm working, you don't have to do anything for now", which is the opposite of what our action color should convey.

**Comment by lbebber** [comment]
@cmdalbem alright, I think I'm biased because I like it blue, but I think you're right

**Comment by cmdalbem** [comment]
@lbebber I like it blue too lol

**Comment by akaFTS** [comment]
Halting development, branch name is `fix/button-loading` is somebody wants to take over.

**Comment by kevinch** [comment]
Closing, the loading state has now an independent layout.
