### ISSUE TITLE
Tab sample

### ISSUE THREAD

**Issue by fredppm** [vtex/styleguide#306]
**Describe the bug**
This tabs example need be replace. The current reference doesn't exists:
```
required('./tab,js')
```

**To Reproduce**
Copy and past the sample

**Expected behavior**
Quick use of the component

**Screenshots**
NA

**Additional context**
This should be
```
import Tabs from '@vtex/styleguide/lib/Tabs'
import Tab from '@vtex/styleguide/lib/Tabs/Tab
````

**Comment by kevinch** [comment]
@fredppm closing since the example at https://vtex.github.io/styleguide/#tabs look fine to me.
