### ISSUE TITLE
Header main button loading

### ISSUE THREAD

**Issue by fredppm** [vtex/styleguide#307]
I don't know if the guidance to button action exists but when an user click the header button and the action need a time to be complete the button should be marked as loading. 

## Overview

Click on the header main button with delayed action

## Purpose

Response the client click

## Context

The header main button should be able to set state loading. This will help the user don't multi click it.

## Examples

Click on the header main button with delayed action

**Comment by kevinch** [comment]
This has been done in https://github.com/vtex/styleguide/pull/305 @fredppm

**Comment by kevinch** [comment]
Button in header has limited props:
```
{buttonLabel && (
  <Button
    size="small"
    variation="primary"
    neutral
    onClick={this.handleButtonClick}
  >
    {buttonLabel}
  </Button>
)}
```

**Comment by cmdalbem** [comment]
Esses dias eu tava viajando sobre talvez ter outras opções de ações no nivel do PageHeader, com outras combinações de componentes. Pra implementar isso eu tinha pensado em abrir a implementação do componente pra simplesmente aceitar children, que seria "encaixados" naquela região à direita. Ainda nao temos os requisitos e guidelines bem definidos ainda, mas se acharem que essa direção pode ajudar nesse caso de loading levem isso em consideração ;)

**Comment by kevinch** [comment]
Me parece "arriscado" pois ter mais sentido mesmo.

**Comment by cmdalbem** [comment]
@kevinch é arriscado só se não tivermos guidelines que ajudem o dev a usar corretamente. Acho que essa direção resulta numa implementação bem mais simples que a que temos hoje, que temos que manualmente repassar props pro botão. Além disso abre caminho pra usos mais complexos e interessantes.

Exemplificando melhor minha sugestão, imaginei uma API tipo assim:

```
<PageHeader
  title="Order details"
  linkLabel="Orders"
  onLinkClick={e => {}}
>
    <Button variation="tertiary">
        Other action
    </Button>
    <Button variation="primary">
        Main action
    </Button>
</PageHeader>
```

Resultado:
![image](https://user-images.githubusercontent.com/467471/44669216-aed3d500-a9f5-11e8-9a60-66c9b5f41bcd.png)

**Comment by cmdalbem** [comment]
Esse é um exemplo de Admin que desenhamos com mais de um botão no PageHeader:

![image](https://user-images.githubusercontent.com/467471/44669605-b182fa00-a9f6-11e8-9157-620354eddedd.png)

**Comment by kevinch** [comment]
Merged.
