### ISSUE TITLE
Range Slider Component

### ISSUE THREAD

**Issue by brunojdo** [vtex/styleguide#319]
## Overview
The basic slider is horizontal and has two handles to define a range. We can make the component have only one handle too. 

## Purpose
We need this component to deal with the price filter in search results. 

## Examples
<img width="313" alt="screen shot 2018-09-06 at 12 27 18" src="https://user-images.githubusercontent.com/8000984/45167779-3d074280-b1d0-11e8-9f4e-dab6cf1597a9.png">

See an example at Dreamstore: https://lucas--storecomponents.myvtex.com/eletronicos/d?map=c&priceRange=0%20TO%205000

**Comment by amandaespinosa** [comment]
Temos um slider já desenhado, não sei se já ta implementado, mas em questão de estilo, seria uma questão bem simples de adaptar

**Comment by brunojdo** [comment]
@amandaespinosa perfeito. A gente pode ajustar pra o desenho que vocês tiverem. Pode mandar aqui? Dai já podemos abrir o PR.
