### ISSUE TITLE
Render don't reflect state changes after load

### ISSUE THREAD

**Issue by wender** [vtex/styleguide#328]
**Describe the bug**
I created a simple app to apply inventory changes to sellers, this app has a few columns and one of it is "Status", this update runs asynchronously and change the status after processing each item. But I can only see the first change on the first row, if I want to see it with the final status, I have to scroll down.
But if my list is not big enough to scroll, I never see the changes

**To Reproduce**
1. Create a list with several items to a Table
2. Run a process to change the state equivalent to 1 cell for each row sequencially with some interval like 1 second
3. Scroll down to see it changing
4. If you don't scroll, you'll not see any changes

**Expected behavior**
We should see the changes being reflected immediately 

**Screenshots**
![Table](https://media.giphy.com/media/1nbwufxBBrX3zMRyc7/giphy.gif)

**Additional context**
The status information uses Badge inside the cellRenderer function

**Comment by klzns** [comment]
Can you provide some code? 

It might be related on how you're dealing with React `key` prop or React state.

**Comment by cmdalbem** [comment]
I think this one was fixed by https://github.com/vtex/styleguide/pull/335, right @wender (& everyone)?

**Comment by cmdalbem** [comment]
[supposing this was] Fixed by #335.
