### ISSUE TITLE
i18n within the Styleguide

### ISSUE THREAD

**Issue by kevinch** [vtex/styleguide#330]
Think of a way to put i18n translate some labels in components like the Resource list, textarea etc.

**Comment by klzns** [comment]
Why isn't that possible now?

**Comment by cmdalbem** [comment]
A design system that I saw that has internationalisation is Ant Design: https://ant.design/docs/react/i18n
Thinking really macro, I don't quite see why our Styleguide would approach it in a way that isn't integrated with how our Admins do it globally.

**Comment by emersonlaurentino** [comment]
I agree with @cmdalbem , I think the styleguide need not contain internationalization, this should be the responsibility of those using the styleguide. Should this issue remain open?
