### ISSUE TITLE
Textarea with error has no red border

### ISSUE THREAD

**Issue by lbebber** [vtex/styleguide#331]
**Describe the bug**
As the title says

**Expected behavior**
It should probably be red, like the Input with error

**Screenshots**
<img width="922" alt="screen shot 2018-09-13 at 12 03 06" src="https://user-images.githubusercontent.com/5691711/45497039-27a09400-b74d-11e8-9550-a59f850a5a07.png">

**Comment by kevinch** [comment]
@lbebber It is red, but only when focused. @cmdalbem Is that the correct behavior or should we udpate?

![screen shot 2018-09-28 at 14 30 02](https://user-images.githubusercontent.com/2573602/46223916-19e13600-c32b-11e8-849e-26af5373f4cb.png)

**Comment by cmdalbem** [comment]
@kevinch makes sense
