### ISSUE TITLE
Pattern for Icons

### ISSUE THREAD

**Issue by ohmyguigs** [vtex/styleguide#354]
## Overview

Discuss about fixed patterns for icon variations and sizing.

## Purpose

 - Icon sizing (if they could have squared containers to make it easier to apply on different scenarios).
 - Maybe they should have default fixed variations like the Button does. (for example solid, dual color, light etc) (here is a nice example http://styleguide.cumulocity.com/icons/svg-icons/#).

**Comment by kevinch** [comment]
@amandaespinosa

**Comment by cmdalbem** [comment]
do we have updates on this? @ohmyguigs @amandaespinosa
