### ISSUE TITLE
Small Counter

### ISSUE THREAD

**Issue by amandaespinosa** [vtex/styleguide#356]
## Overview

Our counter only has regular, large and extra large versions. A small version is very much needed in mobile and cramped environments, such as the inStore cart.

## Purpose

Allowing cramped scenarios to smoothly bear a counter as a secondary interaction.

## Context

![iphone se 2 27](https://user-images.githubusercontent.com/18710800/46353149-dc81ee80-c631-11e8-98f6-80d4f302aea4.jpg)

PS: Winds of change are happening as we speak, and button and components sizes are being reviewed, it should follow the patterns that are coming next.

**Comment by kevinch** [comment]
Linked with topic on button sizes.

**Comment by cmdalbem** [comment]
@amandaespinosa ainda precisa disso agora que revisamos os tamanhos dos componentes e temos versões menores que antes?

**Comment by lbebber** [comment]
eu acho que ainda precisaria de tamanhos menores no celular, mas acho que é uma questao de diminuir a altura do token `h-small` no celular ao invés de ter algo especifico pro counter.

alem disso, nesse meio tempo o counter ja ganhou o modo "lean" pra ser menos espaçoso

acho que essa issue pode ser fechada, se estiverem de acordo
