### ISSUE TITLE
Table v2

### ISSUE THREAD

**Issue by ohmyguigs** [vtex/styleguide#361]
### Some pending features from v1
 - [x] handle widths properly
 - [x] EmptyState inside content (handle empty search/all columns hidden/0 items)
~~Use Menu component in toolbar for BoxMenus instead of the hardcoded solution~~
 - [x] Handle tons of columns / small and medium sized screens (horizontal scroll)
 - [x] `bg-hover` and `pointer` on row when there is onRowClick

## Overview (v2)

 - [ ] Download button dropdown menu
 - [ ] Bulk actions (checkBoxes and help bar)
 - [x] Density feature in toolbar (with opinionated weights made by @TasGuerciMaia <3)
 - [ ] Finish implementing toolbar style as it is on figma (active menu buttons, hovers etc)
 - [ ] Handle loading natively (with skeleton?)
 - [ ] Finish search input
 - [ ] Card visualization
 - [ ] Resize columns
 - [ ] Line actions
 - [ ] Filter
 - [ ] Import
 - [ ] ~~Stats and consolidated data (?)~~

## Examples
- https://vmware.github.io/clarity/documentation/v0.12/datagrid/
- https://polaris.shopify.com/components/lists-and-tables/resource-list
- http://www.carbondesignsystem.com/components/data-table/code
- https://atlassian.design/guidelines/product/components/tables
- https://ant.design/components/table/
- https://material.io/design/components/data-tables.html
- https://designsystem.quickbooks.com/component/tables/
- https://www.lightningdesignsystem.com/components/data-tables/
- http://ux.mailchimp.com/patterns/tables
- https://www.mapbox.com/base/styling/tables/

_See more references and screenshots on the Figma link below._

## Articles

General
- https://uxdesign.cc/designing-tables-for-reusability-490a3760533
- https://uxdesign.cc/design-better-data-tables-4ecc99d23356

Filters
- https://uxdesign.cc/crafting-a-kickass-filtering-ux-beea1798d64b
- https://baymard.com/blog/horizontal-filtering-sorting-design
- https://uxdesign.cc/designing-better-tables-for-enterprise-applications-f9ef545e9fbd
- https://blog.stephaniewalter.fr/en/essential-resources-design-complex-data-tables/
- https://design-nation.icons8.com/intro-to-data-tables-design-349f55861803
- https://uxplanet.org/how-to-improve-advanced-search-ux-450df698004c

## Work in progress

[→ Roadmap](https://docs.google.com/document/d/1FxKWnPQwK_O3DqFuJ8SO-E_9Nhm8pm-OLWyQvxs0qOk/edit?usp=sharing)
[→ Figma](https://www.figma.com/file/aWaWGvrDNlyNsQKYfrwtsG/Tables?node-id=10041%3A14297)

**Comment by felippenardi** [comment]
@ohmyguigs 	Let's add table `loading` state to the list?

Accepting a `loading` `boolean` prop will trig all rows to display skeletons.
