### ISSUE TITLE
Toast positioning

### ISSUE THREAD

**Issue by TasGuerciMaia** [vtex/styleguide#367]
**Describe the bug**

The toast appears behind the navigation bar. The animation, content and close button are working good. Although there is this positioning problem.

**To Reproduce**

You can see this bug on https://github.com/vtex/logistics-transport
1. Go to pickup point detail page.
2. Click on save pickup point
3. The toast will load on down left corner.

**Expected behavior**

The toast could appear by the navigation bar.

**Screenshots**

<img width="456" alt="screen shot 2018-10-04 at 17 42 13" src="https://user-images.githubusercontent.com/13242383/46501806-e3109180-c7fc-11e8-96de-f47b34f87a7b.png">

**Comment by klzns** [comment]
@TasGuerciMaia can you provide an URL of a linked workspace with this?

**Comment by TasGuerciMaia** [comment]
@klzns https://claraszw--qamarketplace.myvtex.com/admin/pickup-points/new
