### ISSUE TITLE
Fix Header bg

### ISSUE THREAD

**Issue by TasGuerciMaia** [vtex/styleguide#387]
**Describe the bug**
We have to fix header backgoud, changing the current color from bg-muted-5 to none. So we can apply a bg to the whole page.

**Comment by klzns** [comment]
Can you show the use case? Like a print of Figma of what you're trying to achieve?

**Comment by TasGuerciMaia** [comment]
<img width="776" alt="screen shot 2018-10-23 at 16 01 18" src="https://user-images.githubusercontent.com/13242383/47384378-595a3280-d6dd-11e8-8e75-3718210b4e37.png">
Now the header has a background color. It works perfectly with our current background.

<img width="769" alt="screen shot 2018-10-23 at 16 03 42" src="https://user-images.githubusercontent.com/13242383/47384478-a9d19000-d6dd-11e8-8f7a-880569e39cca.png">

My proposal is to remove the header background. By doing it we'll have a component that works with whatever background color we chose to apply now or in the future. In addition to it other people that start using our styleguide will have a flexible component to aply diferent backround colors. Even with tokens, I don't see a point on keeping a background on the component even though it is the same as the background color.

**Comment by kevinch** [comment]
@TasGuerciMaia i will add a possibility to set the background to transparent so that it does not "break" apps that are using and require the background.
