### ISSUE TITLE
NumericStepper "ghost" variation

### ISSUE THREAD

**Issue by hapoza** [vtex/styleguide#393]
## Overview
I think NumericStepper should have a variation similar to Button, following the Button's tertiary variation, where it has less importance on the UI.
This would be great for cases where there are a lot of NumericSteppers on the same screen.

## Purpose
For `vtex.product-customizer`, there's a use case for the NumericStepper where it doesn't have a lot of screen real estate. Other than It being too big, it looks quite bulky compared to the rest of the prototype for Delivery Dreamstore.

## Context
This discussion started on https://github.com/vtex-apps/product-customizer/pull/3, and it made sense that it maybe could be a feature of Styleguide.

## Examples
This is how NumericStepper is by default, it is too big for that use case on mobile screens 
![numeric-stepper-defaults](https://user-images.githubusercontent.com/27775611/47821945-3c5ada80-dd41-11e8-9d13-ac19e295860b.png)

Here's what was done and possibly how it could look:
![numeric-stepper-styled](https://user-images.githubusercontent.com/27775611/47821987-63b1a780-dd41-11e8-85b2-80bf76715bfc.png)

**Comment by gabrielgalc** [comment]
Great, it makes total sense, @hapoza .

**Comment by gabrielgalc** [comment]
Next step would be a PR here with the changes you made on the product customizer, right?

**Comment by hapoza** [comment]
Yes, I can do that!
