### ISSUE TITLE
Input fields don't go back to normal after errorMessage is cleared

### ISSUE THREAD

**Issue by marcelomd** [vtex/styleguide#411]
**Describe the bug**
Input fields don't revert to normal highlight after errorMessage is cleared.

**To Reproduce**
1. Create an Input with custom validation;
2. Set errorMessage;
3. Input becomes highlighted in red. Message is shown;
4. Clear errorMessage;
5. Message disappears;
6. Component is still highlighted in red.

**Expected behavior**
Highlight should revert to non-error state.

**Screenshots**
![screenshot from 2018-11-13 22-29-25](https://user-images.githubusercontent.com/1541938/48452156-e3556280-e794-11e8-8ae1-0bc26594b52b.png)
![screenshot from 2018-11-13 22-29-29](https://user-images.githubusercontent.com/1541938/48452155-e3556280-e794-11e8-9172-bd490f268974.png)
![screenshot from 2018-11-13 22-29-34](https://user-images.githubusercontent.com/1541938/48452154-e2bccc00-e794-11e8-82f5-12f232bd8977.png)

**Additional context**
This is important if we are doing any kind of dynamic field validation.

Input component code shows component error/danger class is set if there are any errors, but there is no provision to remove them if the errors are removed.

Thanks!

**Comment by emersonlaurentino** [comment]
I am closing this issue in order to center this discussion only on issue #936
