### ISSUE TITLE
Image Uploader

### ISSUE THREAD

**Issue by brunojdo** [vtex/styleguide#415]
## Overview

A component that allows the user to upload images. The component must have a way to configure max size and extensions(.jpg, .png) allowed. 

## Context
In PWA admin we need this component.
<img width="188" alt="screen shot 2018-11-14 at 13 03 55" src="https://user-images.githubusercontent.com/8000984/48512212-c446e700-e80d-11e8-944e-48ae7b4f0923.png">

## Examples

Pages Storefront have a sample of this component, Select the Carousel app to see. 
https://storecomponents.myvtex.com/admin/cms/storefront

**Comment by cmdalbem** [comment]
@brunojdo we have a proposal o design for this in the Figma Styleguide already! :)
And from what I remember there are two other variations, designed by @TasGuerciMaia and @gabrielgalc, which might have even been developed already. This can be a great opportunity for us to have One Uploader To Rule Them All.

**Comment by brunojdo** [comment]
@cmdalbem We already have an image uploader in Pages and also in My account. Probably, it was based on @TasGuerciMaia and @gabrielgalc designs.

**Comment by cmdalbem** [comment]
@brunojdo so I guess it's just a matter of talking with these teams so they upload their components to the Styleguide, right?

**Comment by cmdalbem** [comment]
@ntmedina any news on that?

**Comment by emersonlaurentino** [comment]
A component called `Dropzone` was created for this in #671

I will close this issue because it has apparently been resolved. In the meantime, I will open a new issue that two new props be added to Dropzone that specify which extensions are allowed and what is the maximum file size.
