### ISSUE TITLE
New title prop to Box component

### ISSUE THREAD

**Issue by alinevillaca** [vtex/styleguide#453]
**Describe the bug**

With the new pageblock component, there is a possible misinterpretation about its use as titles for boxes. A guideline preventing that was added, but still. Adding this prop to the boxes would help the correct use and would create a pattern for actual box titles.

**Expected behavior**
Use this prop to add a title to a Box component.

**Screenshots**
Wrong use: 
![image](https://user-images.githubusercontent.com/15332517/50026059-b2a05d00-ffce-11e8-83d8-6b220c8e4f0d.png)

Correct use: 
![image](https://user-images.githubusercontent.com/15332517/50026065-bb912e80-ffce-11e8-94f2-fae0fc94fe7e.png)

**Comment by kevinch** [comment]
Closing since https://github.com/vtex/styleguide/pull/869 was merged.
