### ISSUE TITLE
Toggle v2

### ISSUE THREAD

**Issue by klzns** [vtex/styleguide#46]
- [x] Props de tamanho
- [x] Corrigir constraste visual do estado de disable
- [x] Adicionar label

**Comment by klzns** [comment]
https://inclusive-components.design/toggle-button/

**Comment by cmdalbem** [comment]
@alinevillaca reparei que tu reabriu a issue, porém todos itens da descrição ali estão marcados como feito. O que está faltando na tua opinião?
