### ISSUE TITLE
Table - Empty and loading states

### ISSUE THREAD

**Issue by cmdalbem** [vtex/styleguide#481]
Here is a proposal for the Table states.

Empty state - No data from backend
---
![no data](https://user-images.githubusercontent.com/467471/50643167-694f8780-0f54-11e9-9754-f11ad5f3209f.png)

Empty state - no results found for given search
---
![search](https://user-images.githubusercontent.com/467471/50643152-618fe300-0f54-11e9-93bd-653221aecd1b.png)

Loading state
---
![loading](https://user-images.githubusercontent.com/467471/50643030-17a6fd00-0f54-11e9-8347-5c13f0866f82.png)

**Comment by ohmyguigs** [comment]
Nothing to show and no results are already implemented.
and this https://github.com/vtex/styleguide/pull/488 solves the loading :)
