### ISSUE TITLE
Pensar em um Input com ações

### ISSUE THREAD

**Issue by klzns** [vtex/styleguide#50]
Exemplo:
![image](https://user-images.githubusercontent.com/284515/37790587-bd69e514-2de5-11e8-86b3-30f8a1830d9a.png)

**Comment by cmdalbem** [comment]
@klzns como tu acha que poderíamos abordar isso? Disponibilizar algo genérico como um "inset button" pra inputs e deixar que cada um use como quiser?
Eu particularmente acho que o Styleguide fica mais maneiro se já prevemos quais os casos de uso, documentamos eles e fazemos funcionar bem pra eles. Por exemplo o botão de copiar ali, seria legal que as pessoas usem sempre o mesmo ícone e o feedback na tela seja sempre o mesmo, né? Ou se for uma tooltip, que abra uma tooltip que seja consistente na plataforma.
Tu lembra se tinha alguma necessidade e contexto quando abriu essa issue pela primeira vez?

**Comment by cmdalbem** [comment]
@klzns up

**Comment by klzns** [comment]
Acho que sobre implementação poderia ser da mesma forma que fizemos o InputSearch.

**Comment by kevinch** [comment]
Closing since no one seem to need it right now.
