### ISSUE TITLE
Expand on Contributing section

### ISSUE THREAD

**Issue by cmdalbem** [vtex/styleguide#503]
As per recent requests from @brunojdo, people outside of VTEX or those who haven't been attending to the meetings might find a little obscure how to contribute to the project and how requests are handled.

We need then a more detailed guide on how to:
- Run the project locally and code architecture
- Make a PR, new releases, updating the Changelog
- Request new components or help on developing one
- Ask questions and participate in discussions
- etc... (what else?)

# Examples

## Ant (Alibaba)
https://ant.design/docs/react/contributing

## Primer (Github)
https://styleguide.github.com/primer/getting_started/contributing/

## Carbon (IBM)
https://www.carbondesignsystem.com/contributing/designers
https://www.carbondesignsystem.com/contributing/developers

## Pluralsight
https://design-system.pluralsight.com/contribute/

## Quickbooks
https://designsystem.quickbooks.com/contribute/

**Comment by sbaldwin24** [comment]
I'd be willing to contribute. I currently work on a Design System using StyleGuidist; let me know if I can help.

**Comment by cmdalbem** [comment]
Work in progress: https://docs.google.com/document/d/1QzN5yMT-M_mlxEsiefPXYIVh3PhKjJVHHlsgWN_pePE/edit?usp=sharing
