### ISSUE TITLE
Criar componente Fieldset

### ISSUE THREAD

**Issue by klzns** [vtex/styleguide#51]
Exemplo:
![image](https://user-images.githubusercontent.com/284515/37790773-353dbf34-2de6-11e8-8cfd-0e7ae1d67698.png)

https://auth0-cosmos.now.sh/

**Comment by cmdalbem** [comment]
@klzns pode nos ajudar dando mais detalhes dessa demanda?

**Comment by cmdalbem** [comment]
@klzns up
