### ISSUE TITLE
Dropdown click action problem on mobile

### ISSUE THREAD

**Issue by kevinch** [vtex/styleguide#523]
**Describe the bug**
The click event is not triggered on the whole element on mobile.

**To Reproduce**
1. Open a page that uses the Dropdown on a mobile (ex cea.myvtex.com/admin/insights)
2. Click on 'the Data Analysis Dropdown

**Comment by emersonlaurentino** [comment]
@kevinch I could not reproduce the problem. Does this problem still persist?

**Comment by kevinch** [comment]
Tested and could not reproduce anymore. Closing.
