### ISSUE TITLE
Collapsable Card

### ISSUE THREAD

**Issue by klzns** [vtex/styleguide#53]
Boa referencia de usabilidade:
https://inclusive-components.design/collapsible-sections/

**Comment by cmdalbem** [comment]
Rascunhei um aqui quando tava fazendo o app do Google Shopping mas acabamos não usando: https://www.figma.com/file/a94lX91ZmYGIDBxvb8shwLn8/VTEX-Design?node-id=148%3A962
O que vcs acham?

**Comment by brunojdo** [comment]
Natalia fez um collapse para o pages-editor. Iremos implementar, que tal fazermos uma PR no Styleguide tb? https://www.figma.com/file/06qJofEJKlBWfQlikoFjC2fH/Pages-Experience?node-id=603%3A179

**Comment by cmdalbem** [comment]
@brunojdo bacana, mas no link não achei nenhum card. A ideia seria criar um componente "collapsible" genérico, ou embedar esse comportamento em um Card pra criar um componente de "collapsable card" propriamente dito?

**Comment by brunojdo** [comment]
Imagino que a ideia seria um collapsable genérico. Pedi para Oldufre adicionar aqui na thread a proposta com a implementação que fizemos no pages-editor. Fizemos um collapsable card e tambem fizemos um accordion, que é basicamente um "collapsable card group"

**Comment by cmdalbem** [comment]
@oldufre bem legais teus estudos!
Acho esse componente um ótimo acrescimo pro styleguide. O próximo passo pra conseguir implementá-lo é pensar como seria a API desse componente: o que tu acha que deveria ser customizável nele, e o que é fixo e opinionado? O quão flexível vamos deixar ele, pra poder ser usado em vários contextos diferentes, mas sem ser flexível demais que abra margem pra ser usado de maneiras "estranhas"? Por exemplo, tu acha que o desenvolvedor poderia pôr _qualquer_ coisa na parte interna dele ali, ou só um corpo de texto mesmo? Quantos níveis de "nesting" nós vamos permitir: só dois, ou vamos permitir usar o componente de maneira recursiva pra que possa ter quantos níveis o desenvolvedor precisar?
Algo que ajuda bastante neste momento é coletar da galera onde que eles pensam em usar o componente pra testar se o design funcionará em contextos diversos. Por exemplo: talvez alguém queira usá-lo com uma largura bem maior que as que tu desenhou, e nesse caso talvez o affordance fique comprometido porque o caret ficará muito longe do texto. Se for o caso, daí talvez tenhamos que fazer as bordinhas mais nítidas, ou talvez tenhamos que mover o caret pro lado esquerdo do componente pra manter eles sempre próximos.

**Comment by brunojdo** [comment]
Sobre esse ultimo ponto, minha visão é que todo a barra seja clicavel pra abrir/fechar o card, assim o caret fica mais um apoio visual do que necessariamente funcional. O que acha? Já vi algumas implementações assim e gostei.

**Comment by cmdalbem** [comment]
@brunojdo parece uma boa direção! 
Minha hipótese é que questão do caret estar longe do texto influencia na própria percepção do usuário sobre aquele componente ser interativo, sabe? Tô preocupado com o affordance mesmo.

**Comment by oldufre** [comment]
Oi @cmdalbem, boa tarde, vlw pela observações ^^

Respondendo, acho que a largura pode ser customizada, pois para um menu de app ele ocupará 80% da tela, segundo o tachyons, já se ele tiver na tela normal pode ser preenchido a largura da tela toda.

A quantidade de sessões não serão limitada, exemplo do menu, varia bastante, ainda não vi problemas com isso até então(pesquisar mais).

Sobre a quantidade de níveis, teremos só quatro no momento que será: section, sub section, subsub section e subsubsub section. 

Com relação ao que pode ser adicionado, só tínhamos pensado em link e textos, mas poderia se uma boa colocar imagens, imagem e texto junto também, mas faremos isso depois.  

Sobre o caret ficar longe, realmente, se for em web acredito que ficará bem longe, mas foi assim que achei na pesquisa que fiz, mas para formatos menores a disposição dele normalmente é a direita e seguindo o material de você ele são sempre a direita.

Se puder falar mais coisas que observou iria ajudar muito =D

**Comment by oldufre** [comment]
Oi @cmdalbem, boa tarde, vlw pelas observações ^^

Respondendo, acho que a largura pode ser customizada, pois para um menu de app ele ocupará 80% da tela, segundo o tachyons, já se ele tiver na tela normal pode ser preenchido a largura da tela toda.

A quantidade de sessões não serão limitada, exemplo do menu, varia bastante, ainda não vi problemas com isso até então(pesquisar mais).

Sobre a quantidade de níveis, teremos só quatro no momento que será: section, sub section, subsub section e subsubsub section.

Com relação ao que pode ser adicionado, só tínhamos pensado em link, textos e imagens.

Sobre o caret ficar longe, realmente, se for em web acredito que ficará bem longe, mas foi assim que achei na pesquisa que fiz, mas para formatos menores a disposição dele normalmente é a direita e seguindo o material de você ele são sempre a direita.
Concordo com Bruno em o box todo ser clicável, a não ser quando se tem mais de um ícone com funções deferentes, aí teria que apertar nele msm.

Se puder falar mais coisas que observou iria ajudar muito =D

**Comment by cmdalbem** [comment]
@oldufre valeu pelas réplicas! Andei pensando melhor sobre algumas coisas, vê o que tu acha:

- Tu acha que é _bastante_ importante a gente limitar a 4 níveis, ou podemos deixar isso em aberto? acredito que pra implementação é mais simples se deixar em aberto mesmo.
- Mesma coisa pro conteúdo: acredito que o mais simples é deixar aberto pra pessoa pôr o que quiser dentro. O componente ficaria mais flexível, atendendo a mais casos de uso. O que tu acha?
- Dei uma olhada rápida nas nossas referências de design systems e parece ser unanimidade que o caret fique na esquerda ([IBM](http://www.carbondesignsystem.com/components/accordion/code), [Quickbooks](https://designsystem.quickbooks.com/component/accordion/), [Salesforce](https://www.lightningdesignsystem.com/components/accordion/), [Alibaba](https://ant.design/components/collapse/)). Provavelmente tem a ver com esse uso na web, mas é difícil tomar essa decisão sem ter mais contexto de como as pessoas vão querer usar. Vou tentar ver quem mais pode tá precisando disso agora, pra gente ver se é mais comum usarem pequeno ou grande.
- Reparei que na implementação que está no PR existe a possibilidade de customizar o ícone de caret pra ser outro ícone qualquer. Tenho a impressão que nesse ponto poderíamos ser mais opinionados sobre o ícone, pra manter mais a consistência na plataforma. O que tu acha?

**Comment by cmdalbem** [comment]
Maneiro!

Sobre o lado do caret, eles são diferentes pq são usos muito diferentes, né? Um é uma coisa, outro é outra - mas que fica engraçado assim junto, fica mesmo.
Mas é como tinha falado, é difícil tomar uma decisão sobre qual vai ser mais usado sem ter mais contexto, e talvez o contexto que a gente precisa venha com o tempo :)

**Comment by cmdalbem** [comment]
This is now possible with the Collapsible componente (https://github.com/vtex/styleguide/pull/595).
