### ISSUE TITLE
Dropdown click action problem

### ISSUE THREAD

**Issue by marceloneias** [vtex/styleguide#532]
**Describe the bug**
The click event is not triggered on the whole element.

**To Reproduce**
1. Open a page that uses the Dropdown.
2. Click on arrow or any other place (see screenshot below).
3. The Dropdown doesn´t open in some cases.

**Expected behavior**
The Dropdown should open when user click in any place of dropdown.

**Screenshots**
![vtex-dropdown-issue](https://user-images.githubusercontent.com/6405250/52489943-bdc8d100-2baa-11e9-90f5-b0939d41906f.gif)

**Comment by ohmyguigs** [comment]
I have a PR with this fix 😄 
https://github.com/vtex/styleguide/pull/520
just some more tweaks and I'll release it. 👍

**Comment by marceloneias** [comment]
Thank you guys, it worked perfectly!!
