### ISSUE TITLE
Mobile modal

### ISSUE THREAD

**Issue by kevinch** [vtex/styleguide#539]
Adapt our modal to mobile views. Check design with @amandaespinosa .

**Comment by amandaespinosa** [comment]
Btw, I believe the changes in regards to spacing and typo hierarchy would be very flattering to the desktop version as well.

![modal_mobile](https://user-images.githubusercontent.com/18710800/53109961-c90bed00-3518-11e9-8c44-1b909afae927.png)

**Comment by kevinch** [comment]
Implemented.
