### ISSUE TITLE
Table - Cannot use sortable & headerRenderer together

### ISSUE THREAD

**Issue by kevinch** [vtex/styleguide#548]
**Describe the bug**
In a table schema, we cannot use both features `sortable` to allow a column to be sorted and `headerRenderer` to customize the rendered value of the column's title.

This is due to this block of code (shortened for brevity) https://github.com/vtex/styleguide/blob/master/react/components/Table/SimpleTable.js#L167:
```
{schema.properties[property].sortable ? (
  <span onClick={}>
    {`${title} `}
  </span>
) : columnIndex === 0 && fixFirstColumn ? (
  <div>
    <span>{title}</span>
  </div>
) : headerRenderer ? (
  headerRenderer({...})
) : (
  title
)}
```

The ternary would require a small update.

**Expected behavior**
A sortable column should allow as well a custom header.

**Comment by ohmyguigs** [comment]
In the new Table component documentation there is a section about this.
Using the two together is not supported indeed. And it should not be supported natively.
If you are going to customize the header with `headerRenderer ` you can manually implement sort behaviour.
