### ISSUE TITLE
Drag zone for file upload

### ISSUE THREAD

**Issue by cmdalbem** [vtex/styleguide#549]
A simple drag zone component to standardize how we deal with it in the Admins.

![image](https://user-images.githubusercontent.com/467471/53021945-09943980-3439-11e9-9828-af5c80529c61.png)

**Comment by cmdalbem** [comment]
@claraszw1 has it implemented on Pickup Points Admin already, no need to implement from scratch :)

**Comment by cmdalbem** [comment]
@amandaespinosa I think I saw an implementation of this component in your InStore Admins, right?

**Comment by cmdalbem** [comment]
Not sure, but this might be a duplicate of https://github.com/vtex/styleguide/issues/415

**Comment by thaynamatos** [comment]
@cmdalbem is it possible to upload more than one doc in this example?

**Comment by cmdalbem** [comment]
@thaynamatos the state after this initial one was not defined and is up to each designer/developer implement it, so yes, you could have it accept multiple files.
In the future could be nice to also standardize the other states, my aim here was to have some kind of MVP because several different admins were already implement it slightly different.

**Comment by kevinch** [comment]
wip at https://github.com/vtex/styleguide/tree/feature/dropzone

**Comment by cmdalbem** [comment]
Implemented by https://github.com/vtex/styleguide/pulls?utf8=✓&q=dropzone
