### ISSUE TITLE
Radio Button

### ISSUE THREAD

**Issue by klzns** [vtex/styleguide#55]

**Comment by gabrielgodoy** [comment]
Referência no [Figma](https://www.figma.com/file/RauaNQiPf9uOq6nMVlbmpdFL/Styleguide)

![image](https://user-images.githubusercontent.com/2944970/38737284-22237e5e-3f05-11e8-9b6c-18ffc5f78cbd.png)

**Comment by cmdalbem** [comment]
Design pronto no novo Figma: https://www.figma.com/file/a94lX91ZmYGIDBxvb8shwLn8/VTEX-Design?node-id=228%3A37

**Comment by gabrielgodoy** [comment]
Abri o [PR](https://github.com/vtex/styleguide/pull/109)
