### ISSUE TITLE
Tabs - disabled state

### ISSUE THREAD

**Issue by cmdalbem** [vtex/styleguide#560]
I've noticed our tabs are missing a `disabled` state, so I draw these:

![image](https://user-images.githubusercontent.com/467471/53575009-7604ec00-3b4f-11e9-80bb-f4eb6b2f1cab.png)

# Example application
![image](https://user-images.githubusercontent.com/467471/53574963-64bbdf80-3b4f-11e9-83f7-f89f20f81083.png)

**Comment by leolanavo** [comment]
Resolved by #565
