### ISSUE TITLE
Toasts

### ISSUE THREAD

**Issue by klzns** [vtex/styleguide#57]
Problema
----------------
Solução genérica para notificar sucessos e erros de ações do usuário em ações de interface assíncronas, comuns em SPAs (Single Page Applications).
Alternativa ao sistema de Alerts, que são _inline_, ou seja, interferem no layout da tela.

**_Que outras diferenças tem entre Alerts e Toasts??_**

Decisões
----------------
- Parâmetros não devem estar totalmente abertos pra cada desenvolvedor usar como quiser. A aparência e o comportamento devem ser o mais similares possíveis pra manter a consistência através da plataforma.
- ...

Módulos que têm essa demanda
----------------
- Credit Control

Casos de uso
----------------
- Após criação de nova conta. Mensagem "Nova conta criada".
- Após sucesso em editar configurações. Mensage "Configurações salvas."

Benchmark
----------------
**Toasts/Flash Messages/Snackbars**
Atlassian: https://atlassian.design/guidelines/product/components/messages
Salesforce: https://www.lightningdesignsystem.com/components/toast/
Quickbooks: https://designsystem.quickbooks.com/component/toast-messages/
Carbon (Inline Notification): http://www.carbondesignsystem.com/components/notification/
Material: https://material.io/design/components/snackbars.html
Ant: https://ant.design/components/message/
Polaris: está marcado como "In development": https://polaris.shopify.com/components/component-status#navigation

**Alerts/Banners**
Atlassian: https://atlassian.design/guidelines/product/components/banners
Salesforce: https://www.lightningdesignsystem.com/components/alert/
Quickbooks: https://designsystem.quickbooks.com/component/inline-messages/
Carbon (Toast Notification): http://www.carbondesignsystem.com/components/notification/
Material: https://material.io/design/components/banners.html
Polaris: https://polaris.shopify.com/components/feedback-indicators/banner
Ant: https://ant.design/components/alert/

Work in progress (Figma)
--------
https://www.figma.com/file/a94lX91ZmYGIDBxvb8shwLn8/VTEX-Styleguide?node-id=4279%3A0

**Comment by cmdalbem** [comment]
Work in progress: https://www.figma.com/file/a94lX91ZmYGIDBxvb8shwLn8/VTEX-Styleguide?node-id=4279%3A0

**Comment by cmdalbem** [comment]
Algumas perguntas em aberto que ainda não tenho contexto suficiente pra responder, nem princípios da plataforma que me ajudem a tomar a decisão.
Me parece que esses não deveriam ser parâmetros em aberto pra cada desenvolvedor decidir, pra que a experiência seja consistente na plataforma.

- Qual canto da tela mostrar? O canto inferior direito parece ser o melhor, porque é o que está atualmente mais livre, mas esse não parece ser um argumento muito forte.
- Timeout: se sim, quanto tempo? Sempre, ou opcional?
- Dar opção de botão de fechar ao desenvolvedor? Isso pode ser usado em conjunto com timeout ou não?
- Múltiplos alerts: opção de "stackar" um em cima do outro - será que é interessante?
- Transição: usar? Qual duração e easing? Com transform, ou só opacidade? 
- Permitir ter um botão dentro?
- Como deve se comportar com textos maiores? A largura deve ser dinâmica ou fixa? Me parece que não é bom permitir usar texto muito grande ali, mas não consigo decidir ainda um tamanho máximo, e se permitimos 1, 2 ou mais linhas.

**Comment by lbebber** [comment]
meus 2¢:

acho que toasts/snackbars sao: 1 - efêmeros, 2 - curtos (quanto à mensagem), 3 - instantâneos, 4 - não obstrusivos, 5 - informativos, mas nao estritamente necessários

o "instantâneo" nao é _necessariamente_ no momento da ação, mas no momento que algo assincrono (erro, sucesso) aconteceu—se a ação for levar a outra página, e a notificação sobre o sucesso ou erro for aparecer nela, usar o alert faz mais sentido.

**Comment by lbebber** [comment]
![mio-design 2fassets 2f1brzeumgixjtfvg7sk-mzcq1ibqxss9fw 2fsnackbars-when-to-use](https://user-images.githubusercontent.com/5691711/43603509-89cd803e-9669-11e8-8a70-ea6edd7145f6.png)

eu ia comentar mais coisas, mas acho esse um bom resumo

**Comment by lbebber** [comment]
e meus 2¢ às perguntas que o dalbem fez:

- Qual canto da tela mostrar?
faz sentido ser o mais livre, pra nao ser obstrusivo, mas isso vai depender da aplicação, então ele deve ser customizavel

- Timeout?
sim, por default, mas opcional 

- Transição: usar? 
sim, qual nao sei

- Permitir ter botões dentro?
é comum ter uma ação esse tipo de componente

- Como deve se comportar com textos maiores? ....
acho que tem que ter tamanho dinamico, mas alertar no console se o texto ta muito grande, pra usar um Alert ou outra coisa; acho que é ruim cortar o texto, porque o desenvolvedor/designer pode nao ter considerado um caso que aparece um texto maior, e o usuário nao iria poder ver essa informação

- Ter um título?
nao

- Múltiplos alerts: opção de "stackar" um em cima do outro - será que é interessante?
Acho que, se nao for muito trabalho implementar, sim, para o usuário nao perder informações; mas talvez devessemos desencorajar o uso

**Comment by amandaespinosa** [comment]
Muitas das perguntas acima já foram respondidas nas novas premissas do doc. 

Sobre comportamentos:
- Toast do not persist on the user's page. It also does not wait for user action to appear.
- Its position is bottom-left of the page, after the drawer if there is one.  
- Toasts need prior user action to appear.

**Comment by amandaespinosa** [comment]
Surgiu demanda para desenvolvimento desse rapaz pro inStore! Temos outros cenários que estão pedindo toasts tb? Alguém já se prontificou pra fazer?

**Comment by klzns** [comment]
Acho que o @lbebber tava fazendo, @amandaespinosa

**Comment by cmdalbem** [comment]
Fixed by https://github.com/vtex/styleguide/pull/342 (& others)
