### ISSUE TITLE
Tab

### ISSUE THREAD

**Issue by klzns** [vtex/styleguide#58]
Problema
----------------
Elemento de navegação interna.
"Tabs make it easy to explore and switch between different views." (Material)

Demanda
----------------

- Credit Control

Referências
----------------

- https://uxplanet.org/tabs-for-mobile-ux-design-d4cc4d9410d1
- https://material-ui-next.com/demos/tabs/
- https://semantic-ui.com/modules/tab.html
- https://material.io/guidelines/components/tabs.html#tabs-usage

**Comment by cmdalbem** [comment]
Design: https://www.figma.com/file/a94lX91ZmYGIDBxvb8shwLn8/VTEX-Design?node-id=191%3A1823

**Comment by cmdalbem** [comment]
Temos isso implementado já no Credit Control, é só extrair o componente.

**Comment by kevinch** [comment]
Dev direction https://codesandbox.io/s/jzyk7qk0yw
