### ISSUE TITLE
Table

### ISSUE THREAD

**Issue by klzns** [vtex/styleguide#60]

**Comment by klzns** [comment]
https://www.figma.com/file/EKQQlffEG0Hl2z2hwuat11Oj/colllections_hackaton

**Comment by caiopimentel** [comment]
Older:
https://www.figma.com/file/EKQQlffEG0Hl2z2hwuat11Oj/colllections_hackaton

**Comment by klzns** [comment]
Boa referencia de design:
https://inclusive-components.design/data-tables/

**Comment by ohmyguigs** [comment]
:) https://github.com/vtex/styleguide/pull/177

**Comment by cmdalbem** [comment]
@klzns apesar de ter várias melhorias à vista, já temos uma versão bem simples e read-only no Styleguide. O que tu acha: fechamos esse ticket aqui, ou populamos ele com mais requisitos?

**Comment by cmdalbem** [comment]
Fechando esse ticket já que já temos um componente simples de tabela no Styleguide. Quando tivermos novas demandas pra esse componente criamos novos tickets pra isso.
