### ISSUE TITLE
Tag input with Autocomplete / Multiselect

### ISSUE THREAD

**Issue by klzns** [vtex/styleguide#61]

**Comment by klzns** [comment]
https://www.figma.com/file/dohzIT9SnFFWEccxx4EcdBnR/Tag-input-with-autocomplete
por @rsimoens

**Comment by cmdalbem** [comment]
Movemos os desenhos do Simoens pra dentro do projeto do Styleguide: https://www.figma.com/file/a94lX91ZmYGIDBxvb8shwLn8/VTEX-Styleguide?node-id=148%3A969

**Comment by jullyanav** [comment]
Estou começando a desenvolver com base nos desenhos do Simoens. Precisamos sincronizar para conferir se é assim mesmo que a gente quer.

**Comment by jullyanav** [comment]
Alguém tem necessidade de limitar o número de tags selecionáveis?
