### ISSUE TITLE
Checkbox label is not clickable when you don't pass id prop

### ISSUE THREAD

**Issue by ohmyguigs** [vtex/styleguide#613]
**Describe the bug**
 Clicking the checkbox input works fine, but clicking the label when there is no id prop does nothing.

**To Reproduce**
![checkbox-id-click-bug](https://user-images.githubusercontent.com/8530905/55979019-8f797780-5c67-11e9-9061-80f00509ec29.gif)

**Expected behavior**
 - Either id prop must be required or clicking the label should work without it

**Comment by klzns** [comment]
I think `id` should be required

**Comment by ohmyguigs** [comment]
@klzns is this a breaking change?

**Comment by kevinch** [comment]
On it with the Checkbox 3rd state "partial".
