### ISSUE TITLE
Tooltip

### ISSUE THREAD

**Issue by klzns** [vtex/styleguide#62]
## Overview

Tooltips are floating labels that bring quick and contextual information about something in the UI.

## Purpose

- To explain briefly a feature or option upon clicking or hovering a standard tooltip icon (something like a little `i` or `?` icon, to be defined)
- To explain a button without label (probably by hovering its icon)
- A modal could be used for a similar effect, but we doesn't seem to need to interrupt the user if it's a quick tip. However we might suggest using a Modal if the content ends up too big for a Tooltip.

## Context

Conditions Builder
![image](https://user-images.githubusercontent.com/39499441/43491476-210eb8b6-94fb-11e8-8f75-129d1b81e787.gif)

Admin navbar

![image](http://g.recordit.co/gy8Fy951QM.gif)

## Examples

Benchmark:
https://polaris.shopify.com/components/overlays/tooltip
https://atlassian.design/guidelines/product/components/tooltips
https://vmware.github.io/clarity/documentation/v0.12/tooltips
http://www.carbondesignsystem.com/components/tooltip/code
https://www.lightningdesignsystem.com/components/tooltips/

**Comment by kevinch** [comment]
PR at https://github.com/vtex/styleguide/pull/30
On hold due to https://github.com/vtex/styleguide/issues/52

**Comment by kevinch** [comment]
PR: https://github.com/vtex/styleguide/pull/94

**Comment by kevinch** [comment]
On hold since not required by any app right now.

**Comment by brunojdo** [comment]
We need this component in login app. :D

**Comment by cmdalbem** [comment]
We'll need this for Google Shopping App! Can we move forward with the PR?

**Comment by jullyanav** [comment]
The conditions-builder app has tooltips in it, however they are sightly different from the idea on this thread. We are using a React component called [Maple ToolTip](https://www.npmjs.com/package/reactjs-mappletooltip) to show a tooltip on hover (not by clicking).

![edit_tooltip](https://user-images.githubusercontent.com/39499441/43491476-210eb8b6-94fb-11e8-8f75-129d1b81e787.gif)

In this scenario, we have a simple button, supposedly clear enough by it's appearance/context, but we opted for showing a tooltip to be extra clear of our intents.

**Comment by jullyanav** [comment]
I wasn't planning to. I suspect we still need some design work?

**Comment by kevinch** [comment]
Closing since no one needs it right now. @klzns has one that can be implemented.
