### ISSUE TITLE
Floating action bar

### ISSUE THREAD

**Issue by cmdalbem** [vtex/styleguide#635]
A simple floating footer component for admin pages that are in a state of "edit mode".

- The component should, for now, only work with the `SAVE` and `CANCEL` default-sized buttons. If more complex scenarios come up in the future we can surely revisit this contract!
- The bar should always stick to the bottom of the viewport.
- The bar horizontal padding should be the same of the underlying Layout component. The vertical padding is 16px.
- The bar shadow is the "active shadow" type (same as the Popover): `box-shadow: 0px 1px 18px rgba(0, 0, 0, 0.14);`

Any questions please feel free to ask :) 

![image](https://user-images.githubusercontent.com/467471/57321593-10495900-70d8-11e9-8817-8eb26ea5a2a4.png)

**Comment by TasGuerciMaia** [comment]
@cmdalbem we might should change a bit this component in order to follow the pattern that go commerce is already using. What do you think?
