### ISSUE TITLE
String props should also accept FormatedMessage

### ISSUE THREAD

**Issue by anitavincent** [vtex/styleguide#677]
**Describe the bug**
The project still has string parameters that don't accept FormattedMessage. Some components give warnings but still work. Some components give warnings and don't work properly.

When you pass a FormattedMessage component to the search input as a placeholder it causes a console warning and the search input just shows "[Object object]" as a placeholder.

Using FormattedMessage on page header works but causes the warning `Warning: Failed prop type: Invalid prop `title` of type `object` supplied to `PageHeader`, expected `string`.`

Using FormattedMessage on the tab component works, but the value is being used as key too. Causing the warning `Warning: Encountered two children with the same key, `[object Object]`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.`. This also makes react less efficient.

The labels for the Table component in general don't accept FormattedMessage, causing several warnings.

Using formattedMessage with the checkBox component also causes a warning.

**To Reproduce**
Pass a `<FormattedMessage />` component to the input as a placeholder and check the result.

**Expected behavior**
Proper text showing and no console warnings.

**Screenshots**
![image](https://user-images.githubusercontent.com/8623116/59370546-22db3180-8d19-11e9-834a-3e339cdc9468.png)

![image](https://user-images.githubusercontent.com/8623116/59371353-28d21200-8d1b-11e9-8d64-a996ce766938.png)

**Comment by Klynger** [comment]
I don't think it can work in a `<Input />` component, since the `placeholder` prop is just passed down the `placeholder` of the native input, that expects a string. As an alternative you could use `intl.formatMessage({ id: 'id-of-my-message', defaultMessage: '' })`

**Comment by kevinch** [comment]
@anitavincent i think that you should list the exact places where you'd need this and/or create a PR for this.

**Comment by kevinch** [comment]
Closing. We'll keep what's been updated so far as is and keep on using `intl.formatMessage()` in our apps.
