### ISSUE TITLE
Remove hard-coded colors from Button

### ISSUE THREAD

**Issue by lbebber** [vtex/styleguide#680]
**Describe the bug**

The Button component has some hard-coded colors due to the lack of some tokens.

https://github.com/vtex/styleguide/blob/master/react/components/Button/index.js#L160

The tokens should either be created, or these colors should derive from some current token.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by kevinch** [comment]
Update:
```
if (isActiveOfGroup && !disabled) {
      style.backgroundColor = '#0c389f'
      style.borderColor = '#0c389f'
    }
```
https://github.com/vtex/styleguide/blob/master/react/components/Button/index.js#L188

**Comment by cmdalbem** [comment]
This seems to have been fixed. Can you confirm @lbebber ?

**Comment by jonathasbsouza** [comment]
This seems to be fixed. Thanks everyone!
