### ISSUE TITLE
BulkActions - Select All seems reversible

### ISSUE THREAD

**Issue by rafarubim** [vtex/styleguide#688]
**Describe the bug**

When using BulkActions, if you click `SELECT ALL` then unselect one of the rows, it will seem like it's unselected but it is still selected.

**To Reproduce**

Anywhere the table is used, following the steps above will reproduce this behavior.

**Expected behavior**

When `SELECT ALL` is pressed, all rows' checkboxes could be disabled so they can't be unselected. That way, the user would have to click the `X` in the BulkAction bar to cancel the selection.

**Screenshots**

![image](https://user-images.githubusercontent.com/22064061/59450099-d9edb080-8dde-11e9-9968-7e361a65b606.png)

**Comment by cmdalbem** [comment]
makes sense @rafarubim

**Comment by kevinch** [comment]
Closing. This has already been fixed.
