### ISSUE TITLE
Sortable columns ignores headerRenderer

### ISSUE THREAD

**Issue by joaopedroxavier** [vtex/styleguide#700]
**Describe the bug**
If you have a sortable column in your table, you can't redefine what's rendered in its header by the headerRenderer. If there's no title, the header renders the name of the column in the schema

**To Reproduce**
- go to https://styleguide.vtex.com/
- access the `Table` component page
- in the sortable table example, remove the title in the sortable column 'name'. Its name will change from 'Name' to '**name**', since it's sortable and the name of it in the schema is 'name'.
- create a custom `headerRenderer` to this column, and return a simple string in it. It should change the name of the header to that string you return...
- ...but it doesn't change =(

**Expected behavior**
I believe headerRenderer was supposed to have more priority than the name of the column given in the schema. In this case, the returned value from headerRenderer should be the one rendered in the header.
However, that's discussable since the strict way sortable columns headers are rendered: _They render their corresponding title in bold text_. If there is any reason to create a more customized header for a sortable column, this should be fixed.

**Screenshots**
[table](https://drive.google.com/file/d/1qwN3Phz0PZCEq66OUsvKJ3Xiz3fnisuZ/view?usp=sharing)
[code](https://drive.google.com/file/d/1XS6CIeCSJM4_m6DJCOE2kTfrfnVDATEs/view?usp=sharing)

**Comment by ericreis** [comment]
This is not a bug, is a documented behavior of the table component, as you can see below. If you use the `headerRenderer` prop the `sortable` prop becomes useless. For that, you should never use those properties together.

![image](https://user-images.githubusercontent.com/5971264/61074859-11a44400-a3ef-11e9-8663-65abfea10043.png)
