### ISSUE TITLE
Items selection remains marked after making a new search

### ISSUE THREAD

**Issue by matheusfurtado96** [vtex/styleguide#703]
**Description**

If you make a search and mark the selection boxes, when you make a new search the boxes remain marked but on different items of the list.

**To Reproduce**

1. Search for any product - http://prntscr.com/o81e6z
2. Mark some selection boxes - http://prntscr.com/o81eb5
3. Make a new search - http://prntscr.com/o81ef1

The list will keep rendering the items selected on the last search.

**Expected behavior**

It's expected that when you make a new search, the selection boxes get unmarked. Because, as it's a new search, the result has a completely different context.

**Comment by ericreis** [comment]
@kevinch Is this an expected behavior of the table component?

**Comment by matheusfurtado96** [comment]
- [ClubHouse card](https://app.clubhouse.io/vtex-dev/story/15311/items-selection-remains-marked-after-making-a-new-search)

cc: @laerc

**Comment by laerc** [comment]
issue closed by PR https://github.com/vtex/styleguide/pull/728
