### ISSUE TITLE
Totalizers should be a component

### ISSUE THREAD

**Issue by anitavincent** [vtex/styleguide#705]
## Overview

The totalizers component used inside the table should be available as a standalone component.

## Context

The table component uses a totalizer bar that's encapsulated by a component, the totalizer component should be available to be used aside from the table.

**Comment by TasGuerciMaia** [comment]
Yes @anitavincent  we have been discussing it recently. I guess it is a quite simple issue, since it is already developed at the table component. Are you up to creating this component?

**Comment by anitavincent** [comment]
I can work on it yes, if guigs doesn't do it first

**Comment by TasGuerciMaia** [comment]
Accualy I started a brach, now I'm building the documentation. If you can, please take a look if props are working well and stuff. What I did was just separate the totalisers from the table. Although I'm not sure if the component is well designed (code) to be a stand alone component.

**Comment by TasGuerciMaia** [comment]
The pull request is out there #709 :)
