### ISSUE TITLE
Rows per page resets whenever table is re-rendered

### ISSUE THREAD

**Issue by anitavincent** [vtex/styleguide#707]
**Describe the bug**
The number of rows shown on the picker always starts as the first option. If the table re-renders for any reason the picker resets to the initial value. And that's undesirable.

**To Reproduce**
1. Build a table that refetches data when page is changed
2. Change the number of rows per page
3. Change page and that should cause a re-render
4. The number of rows per page will be reset on the rows picker

**Expected behavior**
The picker should conserve the same selected number.

**Screenshots**
![table-rows-bug](https://user-images.githubusercontent.com/8623116/60738482-dc05e380-9f34-11e9-9d14-b51e328d714a.gif)

**Additional context**
This could be fixed by adding a prop 'number of rows per page' to the table.

**Comment by anitavincent** [comment]
This was actually already fixed on a past PR. It's just not documented yet

**Comment by TasGuerciMaia** [comment]
Tá lá :) 

<img width="977" alt="Screen Shot 2019-08-08 at 16 09 45" src="https://user-images.githubusercontent.com/13242383/62730760-06950180-b9f7-11e9-9558-27f1ddb99d28.png">
