### ISSUE TITLE
Items selection remains marked after using the clean button in input

### ISSUE THREAD

**Issue by laerc** [vtex/styleguide#729]
**Describe the bug**
`Table`: Items selection remains marked after using the `x` button to clean the input text.

**To Reproduce**
1. Search for something, like the term `Meia`
![image](https://user-images.githubusercontent.com/36630479/61639944-d3224b00-ac72-11e9-9dc9-78563ce9b91c.png)

2. Select some items using the selection boxes
![image](https://user-images.githubusercontent.com/36630479/61640073-12509c00-ac73-11e9-8043-4925bd07ac37.png)

3. Use the `x` button, to clean the input text
![image](https://user-images.githubusercontent.com/36630479/61640039-01a02600-ac73-11e9-977e-de096a750b63.png)

4. The selection will be kept in wrong items 
![image](https://user-images.githubusercontent.com/36630479/61640084-1bda0400-ac73-11e9-843f-c80e4b33ce38.png)

**Expected behavior**
It's expected that the selection boxes get unmarked after using the `x` to clean the input.

**Additional context**
After talking with @kevinch, he explained that this happens because there is no interaction between the toolbar and the bulk action boxes.

**Comment by kevinch** [comment]
Fixed with https://github.com/vtex/styleguide/pull/874
