### ISSUE TITLE
Dividers

### ISSUE THREAD

**Issue by TasGuerciMaia** [vtex/styleguide#757]
## Overview
Dividers are a usefull component while designing a page that is crowded of information. It is a line, horizontal or vertical that helps to create hierarchy.

## Purpose
Help to separate information when there is no room for a large white space. 

## Examples
![Screen Shot 2019-08-20 at 15 22 16](https://user-images.githubusercontent.com/13242383/63373647-aab76a80-c35e-11e9-84a3-59fe9c17f296.png)
<img width="278" alt="Screen Shot 2019-08-20 at 15 22 10" src="https://user-images.githubusercontent.com/13242383/63373648-ab500100-c35e-11e9-82a7-ebca021acd6e.png">

**Comment by emersonlaurentino** [comment]
This was resolved in https://github.com/vtex/styleguide/pull/864
