### ISSUE TITLE
Floating Action Bar

### ISSUE THREAD

**Issue by TasGuerciMaia** [vtex/styleguide#769]
**Describe the bug**

The component has a buggy behaviour on mobile.
**To Reproduce**

Run the styleguide documentation and change the view mode to mobile. You will see that the component is not rendering on the bottom.

**Expected behavior**

It should work as it works on the desktop mode.

**Screenshots**
![Aug-22-2019 12-51-27](https://user-images.githubusercontent.com/13242383/63530437-d95b4f80-c4dc-11e9-96bd-ead70c6a5f97.gif)

**Comment by emersonlaurentino** [comment]
@TasGuerciMaia This behavior is correct, the problem that happens is not related to the component.

`FloatingActionBar` is a single string and there is no line break, causing the width of the documentation page to be increased.

Possible solutions would be: decrease page title font-size (not possible) or separate words using `Floating Action Bar`.
