### ISSUE TITLE
Read-only input has the same appearance as default state

### ISSUE THREAD

**Issue by davicosta99** [vtex/styleguide#790]
**Describe the bug**
Read-only should be different than the regular input. It's not editable, it has a value that is still valid but it's not disabled. Its appearance should hint at that.

**To Reproduce**
Open the styleguide documentation and see for yourself.

**Expected behavior**
It should share the same background color as the disabled input but retain the inverted base color for text.

**Screenshots**
![Group 4](https://user-images.githubusercontent.com/8797476/63944437-e2ea3780-ca47-11e9-83d5-4422d3509e1b.png)

**Comment by kevinch** [comment]
ref: https://github.com/vtex/styleguide/pull/791

**Comment by kevinch** [comment]
ref: https://github.com/vtex/styleguide/pull/794

**Comment by kevinch** [comment]
Fixed with https://github.com/vtex/styleguide/pulls?q=is%3Apr+is%3Aclosed
