### ISSUE TITLE
Button group

### ISSUE THREAD

**Issue by klzns** [vtex/styleguide#80]
Exemplo: https://getbootstrap.com/docs/4.0/components/button-group/

**Comment by TasGuerciMaia** [comment]
A group of buttons close to each other in the same line column. The minimum group is two buttons. The maximum group is as much as it can fit in the container. For mobile version is recommended the vertical variation.

<img width="1165" alt="Button Group" src="https://user-images.githubusercontent.com/13242383/41173621-0b41fa94-6b2e-11e8-879d-10b0455e6a49.png">

https://www.figma.com/file/a94lX91ZmYGIDBxvb8shwLn8/VTEX-Design?node-id=148%3A968

**Comment by cmdalbem** [comment]
Just documenting what we discussed about this during our meeting a couple of weeks ago:
@TasGuerciMaia's design looks really nice, but the need for this component is still a little nebulous. More context would be needed so we can document and clarify better the expected use cases of this component.
If anyone has a clear need for this component please hop on and help us!

**Comment by cmdalbem** [comment]
Final designs (available in Figma)

![image](https://user-images.githubusercontent.com/467471/52416970-f34dbb80-2ad1-11e9-8cb2-f28396b96060.png)

Figma: https://www.figma.com/file/a94lX91ZmYGIDBxvb8shwLn8/Styleguide-Styles-and-Components?node-id=0%3A1

**Comment by TasGuerciMaia** [comment]
Issue solved on [#640](https://github.com/vtex/styleguide/pull/640
)
