### ISSUE TITLE
Plain button

### ISSUE THREAD

**Issue by davicosta99** [vtex/styleguide#809]
**Describe the need**
We have a tertiary button with props to remove padding on its sides. My proposal is that there should be a plain button that also removes padding on the top and bottom, besides not being all caps.

You can see on the image below two instances were this button variation would be used.

![tertiary](https://user-images.githubusercontent.com/8797476/64045700-5a02f700-cb40-11e9-93db-a184c5f9c88b.png)

**Expected behavior**
It should behave similar to the tertiary button but without it's current footprint and all caps appearance.

Figma: https://www.figma.com/file/LoHnFQmA5FJvapXXWYGhQN/Button?node-id=1%3A45
If you can't access it, talk with me and I'll give you permision.

For reference, see also Polaris' plain button: https://polaris.shopify.com/components/actions/button#navigation

**Screenshots**
![image](https://user-images.githubusercontent.com/8797476/64049526-7d7f6f00-cb4b-11e9-9fd8-7bfa8dca544c.png)

**Comment by ohmyguigs** [comment]
close in https://github.com/vtex/styleguide/pull/886
