### ISSUE TITLE
Busca com filtro

### ISSUE THREAD

**Issue by klzns** [vtex/styleguide#81]
_This is a guide to help get your mental juices flowing, and NOT a rigid and bureaucratic form to be filled out. Scrape everything and start from scratch if it doesn't work for you ;)_

_Let's try to capture the best possible your context and needs so we can design a great component together!_

## Overview

_Explain objectively in a few sentences what this component is about. This is like the component's greeting card._

## Purpose

_- Which problems were you trying to solve when you came up with this?_
_- What use cases would it cover that other components don't?_
_- Are there existing Styleguide components that might be similar but that don't work for you? Why?_

## Context

_It's screenshot time! Don't worry about cropping it, it's good if you capture the full context of your application._

## Examples

_Can you point out to existing solutions in other products that you think would work for you?
Feel free to explore some great Design Systems listed in our References doc: https://docs.google.com/document/d/1-L3xllgWx1nF6mhOryHMw4o8d1_3-AKtC9pGO2VywBg/edit_

**Comment by cmdalbem** [comment]
Eu e o @ohmyguigs estamos trabalhando num componente de filtro bem poderoso no Vtable.
Não tem muita previsão de quando ficará pronto, mas a intenção é extraí-lo e fazer uma API genérica pra atender a casos genéricos.
Se alguém estiver precisando de filtros atualmente e quiser ir documentando suas necessidades aqui na Issue fiquem à vontade!

**Comment by amandaespinosa** [comment]
No inStore, em um futuro próximo, vamos começar o projeto de catálogo e ele vai consistir da busca com filtro. Não comecei a estudar esse ponto específico, mas basicamente seria uma busca de objetivo semelhante à de um e-commerce, buscar por categorias e marcas, de forma mais simplificada.

**Comment by cmdalbem** [comment]
@amandaespinosa legal! Acho que o tipo de filtro que vcs vão precisar é bem diferente do que estamos fazendo. Mas vou formalizar melhor algumas decisões e documentá-las e daí te mostro pra ver o que tu acha

**Comment by cmdalbem** [comment]
Duplicate of https://github.com/vtex/styleguide/issues/285
