### ISSUE TITLE
Enable pagePerSection option

### ISSUE THREAD

**Issue by kevinch** [vtex/styleguide#83]
When the `snap:test` command is fixed with this option that changes the navigation or we found a fix.

Issue: https://github.com/unindented/react-styleguidist-visual/issues/14

**Comment by klzns** [comment]
Acho que ou corrigimos o bug ou não adotamos o `pagesPerSection`.

Prefiro os beneficios do snap do que os beneficios do `pagesPerSection`.

**Comment by cmdalbem** [comment]
Em algum momento no _futuro_ teremos que achar uma solução pra isso. Dado um Styleguide grande o suficiente, a experiência de ter tudo numa página só fica beeem ruim.

**Comment by cmdalbem** [comment]
Uma ideia muito massa pra quando tivermos essa opção de PagePerSection habilitada, pra que a exploração dos componentes seja mais fácil é criar um índice visual como esse aqui: http://www.carbondesignsystem.com/components/overview

**Comment by cmdalbem** [comment]
Numa reunião recente decidimos em grupo que podemos abrir mão da feature de diff visual, dado que a necessidade de termos páginas com menos conteúdo está se tornando mais crítica.
Vou implementar isso como parte do trabalho em https://github.com/vtex/styleguide/pull/377

**Comment by cmdalbem** [comment]
Closed by https://github.com/vtex/styleguide/pull/468
