### ISSUE TITLE
Fix buttons with color set icon

### ISSUE THREAD

**Issue by kevinch** [vtex/styleguide#84]
if you do this:
```
<Button secondary onClick={this.handleClose}>
    <Close icon color={config.colors.blue} size={10} />
</Button>
```

It'll display:
![screen shot 2018-04-06 at 14 43 04](https://user-images.githubusercontent.com/2573602/38435697-dae6d98e-39a8-11e8-8609-aaabe5803dd1.png)

and on hover:
![screen shot 2018-04-06 at 14 43 26](https://user-images.githubusercontent.com/2573602/38435707-e67e0038-39a8-11e8-932c-3e4dbfba6ac2.png)

**Comment by klzns** [comment]
Ja resolvi esse problema no Collections, o código é meio chatinho though.

**Comment by kevinch** [comment]
wip at https://github.com/vtex/styleguide/pull/95

**Comment by kevinch** [comment]
We do it with css `currentColor`.
