### ISSUE TITLE
Add data-attributes prop for e2e tests

### ISSUE THREAD

**Issue by kevinch** [vtex/styleguide#848]
Add the prop `data-attribute` or `data-cy` so that apps using components can pass attributes meant for e2e testing easily and prevent the creation of almost-useless `div` containers.

**Comment by emersonlaurentino** [comment]
I believe it could be used `data-testid` as a convention to define elements that can be found by testing.

We can use the same attribute for testing library and cypress. So you can use the [testing library's getByTestId function](https://testing-library.com/docs/dom-testing-library/api-queries#bytestid) and keep it a good practice for cypress.

>  Best Practice: Use data-* attributes to provide context to your selectors and insulate them from CSS or JS changes.

Ref.: [Best Practices by Cypress](https://docs.cypress.io/guides/references/best-practices.html)

**Comment by kevinch** [comment]
Good point. `data-cy` seems too focused on Cypress while `data-testid` is more generic.
