### ISSUE TITLE
Divider component

### ISSUE THREAD

**Issue by augustocb** [vtex/styleguide#862]
## Overview

Divider is a simple component represent by a line do segregate visually two groups of content. It can be used vertically or horizontally as well.

## Purpose

Nowadays we use borders to divide blocks or list items in layouts. Semantically, they are not borders, but dividers. It's very common to use dividers in Uis (in admins and stores), so this component would be very useful.

## Context and Examples

![Screen Shot 2019-09-30 at 11 56 45](https://user-images.githubusercontent.com/1315451/65891196-877ad480-e37a-11e9-9905-de847630ba3a.png)

**Comment by emersonlaurentino** [comment]
@augustocb what would be the default color using tachyons?

**Comment by augustocb** [comment]
@emersonlaurentino  `b--muted-4` I guess.
