### ISSUE TITLE
Extra Small Button

### ISSUE THREAD

**Issue by matheusps** [vtex/styleguide#877]
##  Overview

Allow `Button` to have a small clickable area to fit on containers that have `2rem` size, such as `Table` cells on `high` density.

## Context
![Screen Shot 2019-10-04 at 10 00 16 (2)](https://user-images.githubusercontent.com/6964311/66209674-42161a00-e68e-11e9-96c4-a8a6e3bf3935.png)

## Examples
Create a new size possibility called `extra-small`, `xsmall` or `tiny`. A good size would be `28px`/`1.75rem`, IMO.

**Comment by davicosta99** [comment]
HI @matheusps, I think #809 will solve this use-case as well.

**Comment by jonathasbsouza** [comment]
@matheusps can we close this issue?

**Comment by jonathasbsouza** [comment]
As we are already using PlainButton, I will close this issue.
