### ISSUE TITLE
Spinner not spinning 

### ISSUE THREAD

**Issue by salesfelipe** [vtex/styleguide#92]
Workspace: https://carousel--storecomponents.myvtex.com/carousel
Src code: https://github.com/vtex-apps/carousel/blob/develop/react/Carousel.js

![image](https://user-images.githubusercontent.com/3926634/39012369-a5471ec8-43ea-11e8-9083-bd998b2b3bee.png)

**Comment by kevinch** [comment]
@salesfelipe Me parece ser apenas um problema de versão. 
Atualize por favor seu `package.json` para `"@vtex/styleguide": "2.0.0-rc.37",`. 

A versão `38` está sem tag no repósitorio, foi erro nossa e já estamos corrigindo.

**Comment by kevinch** [comment]
@salesfelipe versão `2.0.0-rc.39` publicada (https://www.npmjs.com/package/@vtex/styleguide).

**Comment by salesfelipe** [comment]
@kevinch  tentei aqui novamente atualizando pra versão 39 e num mudou nada não. :(

https://carousel2--storecomponents.myvtex.com/carousel

Quando to na versão 37 ele volta a pedir pra passar o style do spinner

**Comment by lbebber** [comment]
This has been solved, AFAIK. Reopen or create a new issue if that's not the case.
