### ISSUE TITLE
Progress Component

### ISSUE THREAD

**Issue by emersonlaurentino** [vtex/styleguide#924]
## Overview

I need to create a component that has progress, `ProgressBar` today does not support what I need, so I needed to create a new component. Here is the prototype:

<img width="916" alt="Screen Shot 2019-11-04 at 16 45 15" src="https://user-images.githubusercontent.com/10627086/68152528-9b3dcb80-ff22-11e9-9f01-0287a4f916f3.png">

## Purpose

Here is the implementation of the new `Progress` component.

<img width="868" alt="Screen Shot 2019-11-04 at 16 44 40" src="https://user-images.githubusercontent.com/10627086/68152529-9b3dcb80-ff22-11e9-83f5-ddf31384155e.png">

**Comment by rerissondaniel** [comment]
The value will be the percentage or the value shown in the top right corner? Would be great if that top right corner value could be ommited (maybe a non required prop indicating its value)

**Comment by cmdalbem** [comment]
@emersonlaurentino but we already have a Progress Bar component, right? I think the functionality you need - which is actually what I'd mostly expect of a ProgressBar - could be a new option in the current component.

**Comment by emersonlaurentino** [comment]
@rerissondaniel The value of the progress is the `percentage`.  In my context the information of current value and max value is important, Idk in which context should show the percentage without the current value and max value.

**Comment by emersonlaurentino** [comment]
@cmdalbem yes, It was my initial thought. But I would have a larger job to add these new features and keep existing ones without breaking where today the `ProgressBar` is already used. So I thought it best to create a new component.

**Comment by rerissondaniel** [comment]
@emersonlaurentino Im my specific case I receive the percentage right away from the API, not knowing to which value it refers to, so there would be redundant information (the percentage and a 0/100 in top right corner)

**Comment by emersonlaurentino** [comment]
@rerissondaniel What do you think about having a new prop called `percentage` that is passed the exact percentage value and if it is entered, the max/value props are not used and consequently hidden from the top?

**Comment by salesfelipe** [comment]
Why can't you use the progressbar?

**Comment by emersonlaurentino** [comment]
@salesfelipe i answered up to @cmdalbem

**Comment by rerissondaniel** [comment]
@emersonlaurentino great! could also call it progress, but that's your call =]

**Comment by emersonlaurentino** [comment]
@rerissondaniel I think it's strange, because it would look like this:
```jsx
<Progress progress={30} />
```

that sounds better to me:
```jsx
<Progress percentage={30} />
```

**Comment by emersonlaurentino** [comment]
@rerissondaniel On second thought, we can reuse the `value` prop. if `max` is not passed,` value` will be used as a direct percentage. so only `value` would be the required prop and we would save a prop.

**Comment by mateusbolsoni** [comment]
I think this "larger job" to add a new feature to our current Progress Bar is the main reason We are trying to use a Design System and not custom components everywhere. I guess you can think more about that before create new components.

**Comment by Klynger** [comment]
Maybe this `percentage` could receive a string to make it possible to support other design options like uploading multiple files and displaying the number of files that were uploaded already

**Comment by emersonlaurentino** [comment]
>Acho que esse "trabalho maior" para adicionar um novo recurso à nossa barra de progresso atual é a principal razão pela qual estamos tentando usar um sistema de design e não componentes personalizados em todos os lugares. Eu acho que você pode pensar mais sobre isso antes de criar novos componentes.

@mateusbolsoni  It turns out that steps don't make sense in progress with percentages. Because there is only one step that would be progress itself. If modify the `ProgressBar` component, it would probably break at some point, and honestly as styleguide will be migrated to the new architecture, I believe the best approach is to create a new component.

**Comment by augustocb** [comment]
We should think about improving that component to support the same features of `ProgressBar` component. So, in the future, we'll have a single component for all cases.

Regarding to the numbers, I would suggest to choose just one of the options to be shown: n% OR x/y. Showing both looks redundant to me.

**Comment by emersonlaurentino** [comment]
> We should think about improving that component to support the same features of ProgressBar component. So, in the future, we'll have a single component for all cases.

@augustocb Yes, I agree with you!

> Regarding to the numbers, I would suggest to choose just one of the options to be shown: n% OR x/y. Showing both looks redundant to me.

@rsimoens can you talk better about it?

**Comment by emersonlaurentino** [comment]
Guys, talking to @rsimoens, we thought it would be more interesting for the component to just render the bar without extra information.

```jsx
<Progress percent={30} />
```

<img width="797" alt="Screen Shot 2019-11-04 at 18 21 05" src="https://user-images.githubusercontent.com/10627086/68159120-e9a59700-ff2f-11e9-8e1a-3f7e48ec8b47.png">

**Comment by ericreis** [comment]
I think you should not add more complexity to who is using the component.

**Comment by emersonlaurentino** [comment]
@ericreis Why would it be more complex to use the component?

**Comment by emersonlaurentino** [comment]
It would make sense to leave the percentage value and `value` and `max` since our interfaces are standardized. However, in the context where I need it it is positioned at the top, in other interfaces it makes no sense to be at the top. And to support choosing the position where the percentage will be rendered seems to me to be downside since the only thing that will maintain consistency is the font size and color, not the position.

I will leave this issue open for a better discussion on Thursday. It was very productive so far, thank you all.

**Comment by ericreis** [comment]
> @ericreis Why would it be more complex to use the component?

This: 
> ... the information of what stage is in or how many percent is (in numbers) would be the responsibility of who is rendering the Progress component

**Comment by emersonlaurentino** [comment]
Seeing that you didn't like the idea that the percentage number and `value` and `max` are the responsibility of the renderer of `Progress`. How do you suggest you stay?

Because in my context the top left `percentage` and the top left `value/max` fit perfectly, but in other cases that doesn't make sense. Give us use cases to create a component that meets our needs.

**Comment by ericreis** [comment]
Maybe the default value of `max` is `100`, that way if developers don't use this prop the value is already the percentage and we can omit the `value/max` in the UI. Otherwise, we show both modes in the UI and calculate the percentage (`value/max`).

I think this should be enough for the `v1` and when more use cases come we can discuss about adding more props to omit fields in the UI.

**Comment by emersonlaurentino** [comment]
@ericreis honestly i don't like components that have props that omit things, it sounds like the component was created for one scenario only and when it is put in other scenarios it needs props to hide things (like overfitting). And the value of prop `max` can be any number, not necessarily 100, because it would be the number of items to process. The `percentage` value is the division between `max` and` value`.

**Comment by emersonlaurentino** [comment]
At the meeting, it was decided that we will rename the current component (ProgressBar) only to `Progress`. Because there are different types of progress (steps and line) and it makes no sense to create new components for this. The component will receive two new props: `type` to define whether to render the step or line component; And `percent`, which will actually add a progress bar.

**The behavior of the current component will be maintained.**

`max` and `value` will not be rendered by the `Progress` component. This will be the responsibility of those who are using the component, as this information was only useful to calculate the percentage of the bar. Now we get a prop called `percent` that has this purpose.

The percentage value for now will not be rendered by the component either and it will be the responsibility of those using the component because we do not have a positioning pattern for that percentage. **This will be a problem that will be solved by our team of designers.**

_That said, I will be closing this issue and opening a new to set the percentage positioning within the Progress component._
