### ISSUE TITLE
Error messages in fields need an icon for color-blind users

### ISSUE THREAD

**Issue by davicosta99** [vtex/styleguide#938]
**Describe the bug**
Outlining the field red and adding a message in red is not enough. Color-blind users need an icon to go along with the message.

**Screenshots**
![1_F7OGfYAElevZDXpyb-QzIw](https://user-images.githubusercontent.com/8797476/68691708-f2f7ba80-0552-11ea-9663-90192dc7f89a.png)

**Additional context**
My first read after discovering this issue is that help messages don't need the icon. They are lighter, and don't need to be as discoverable as an error message.

**Comment by jonathasbsouza** [comment]
I've made an example[ here](https://www.figma.com/file/rnJzqiDzLZ86yicLCrSYIB/02-Forms?node-id=106%3A146) using the Warning icon at 16x16px using the same color as the message text.

**Protanopia**
<img width="314" alt="Screen Shot 2020-03-05 at 16 34 04" src="https://user-images.githubusercontent.com/7189694/76024314-9fe2b280-5f09-11ea-8327-764715c3a952.png">

**Deuteranopia**
<img width="308" alt="Screen Shot 2020-03-05 at 16 34 10" src="https://user-images.githubusercontent.com/7189694/76024320-a2dda300-5f09-11ea-81ad-11f147f02249.png">

**Tritanopia**
<img width="292" alt="Screen Shot 2020-03-05 at 16 34 17" src="https://user-images.githubusercontent.com/7189694/76024325-a53ffd00-5f09-11ea-8043-85776f8cd4db.png">

**Comment by emersonlaurentino** [comment]
closing this issue, because it was resolved in #1077
