### ISSUE TITLE
Capitalization guidelines

### ISSUE THREAD

**Issue by davicosta99** [vtex/styleguide#960]
We currently don't have documentation related to how UI elements should be capitalized. This triggered a discussion between me and @augustocb in our project.

After researching through articles and the documentation of other design systems, I've written a draft with what I believe we should include in the Styleguide documentation.

https://docs.google.com/document/d/1otnxa8qYPWHs40wDFbpna-HVVYAomTyKcY08S2P21pY/edit?usp=sharing

Anyone who wants to contribute can make suggestions in the document or leave a comment in this issue. Thanks!

**Comment by davicosta99** [comment]
**Guidelines from other design systems on this topic**

Polaris (Shopify): https://polaris.shopify.com/content/grammar-and-mechanics#section-capitalization

Carbon (IBM): https://www.carbondesignsystem.com/guidelines/content/guidance/

Salesforce: https://developer.salesforce.com/docs/atlas.en-us.salesforce_pubs_style_guide.meta/salesforce_pubs_style_guide/style_capitalization.htm?search_text=capitalization

Atlassian: https://atlassian.design/guidelines/voiceAndTone/language-grammar

Spectrum (Adobe): https://spectrum.adobe.com/page/grammar-and-mechanics/#Capitalization

**Comment by jonathasbsouza** [comment]
I'll close this because we are solving it at the brand new UX Writing guidelines.
