### ISSUE TITLE
Change font size of content in regular-sized fields

### ISSUE THREAD

**Issue by davicosta99** [vtex/styleguide#964]
**Describe the bug**
The content of our regular sized field is 14pt (Small), such as Input, Dropdown, Numeric Stepper. Our standard font size is 16pt (Body), so we should change the content of these fields to use it. There's no need to change their height, just the font size.

We can leave the label at 14pt for now, but I believe we could explore other solutions in the future for different moments of the interaction.

**To Reproduce**
Look at the input in the context they are applied and you will see that it's font size doesn't match the rest of the screen.

**Expected behavior**
Components with typography styles that match their context and function.

Small: Label (14pt, Small) and Content (14pt, Small)
Regular: Label (14pt, Small) and Content (16pt, Body)
Large: Label (16pt, Body) and Content (16pt, Body)

**Screenshots**
Before
<img width="661" alt="Screen Shot 2019-12-11 at 15 55 04" src="https://user-images.githubusercontent.com/8797476/70650871-a3c6a780-1c2e-11ea-89a8-013aecf10284.png">

After
<img width="667" alt="Screen Shot 2019-12-11 at 15 54 48" src="https://user-images.githubusercontent.com/8797476/70650879-a88b5b80-1c2e-11ea-9547-b8f64ce16cbf.png">

**Additional context**
If you have any comments regarding this change, please leave a comment or reach out to me.

**Comment by davicosta99** [comment]
@augustocb just discovered another compelling reason. iOS zooms in on inputs with content smaller than 16pt, imposing a problem on the user interaction.

https://stackoverflow.com/questions/2989263/disable-auto-zoom-in-input-text-tag-safari-on-iphone

**Comment by jonathasbsouza** [comment]
@davicosta99 I think we can easily deliver this in our next Major update. It's a really simple adjustment that I believe will bring much value to the experience. @emersonlaurentino

**Comment by davicosta99** [comment]
This was already fixed by @augustocb, everyone. This issue wasn't linked to the PR #977, so it wasn't solved automatically as it should. I'll go ahead and do that now.
