### ISSUE TITLE
Modal v2

### ISSUE THREAD

**Issue by cmdalbem** [vtex/styleguide#97]
### Design 
https://www.figma.com/file/a94lX91ZmYGIDBxvb8shwLn8/Smart-Styleguide?node-id=49%3A586
- [ ] Adicionar header
- [x] Definir botões de "OK/cancelar" padrão
- [ ] Fixar padding padrão

### Dev
- [ ] Adicionar header
- [ ] Definir botões de "OK/cancelar" padrão
- [ ] Fixar padding padrão
- [ ] Aumentar área de interação do botão de fechar

**Comment by klzns** [comment]
Corrigir https://github.com/vtex/styleguide/issues/86

**Comment by emersonlaurentino** [comment]
@cmdalbem esse modal já foi implementado?

**Comment by cmdalbem** [comment]
@emersonlaurentino ops essa Issue tá bem desatualizada e não faz mais sentido. Vou fechar ela :)
