### ISSUE TITLE
Re-enable jsx-a11y rules in ESLint config

### ISSUE THREAD

**Issue by lucasecdb** [vtex/styleguide#986]
these rules were disabled in #985, but they are valuable and need to be re-enabled, fixing the issues that come up with them. the rules are:

- [ ] `jsx-a11y/click-events-have-key-events`
- [ ] `jsx-a11y/mouse-events-have-key-events`
- [ ] `jsx-a11y/no-static-element-interaction`
- [ ] `jsx-a11y/no-noninteractive-element-interactions`
- [ ] `jsx-a11y/no-noninteractive-tabindex`
- [ ] `jsx-a11y/label-has-for`
- [ ] `jsx-a11y/no-onchange`
- [ ] `jsx-a11y/no-autofocus`
- [ ] `jsx-a11y/label-has-associated-control`

**Comment by klzns** [comment]
Maybe we shouldn't add those rules back

[From react-a11y](https://github.com/reactjs/react-a11y):
![image](https://user-images.githubusercontent.com/284515/72103987-1cda1d00-3309-11ea-909f-2a0c30d11bc4.png)

**Comment by lucasecdb** [comment]
@klzns fair enough, I think we should replace it in our `eslint-config-vtex-react` then.
