### ISSUE TITLE
Warning when using Dropdown

### ISSUE THREAD

**Issue by salesfelipe** [vtex/styleguide#99]
The dropdown is working fine, but it shows this warning on the console.

Mozilla:
![image](https://user-images.githubusercontent.com/3926634/39306082-8055662e-4935-11e8-92f7-c4259d6fc25e.png)

Chrome:
![image](https://user-images.githubusercontent.com/3926634/39306116-992cd592-4935-11e8-9dbf-4679828e448f.png)

**Comment by lbebber** [comment]
Thanks @salesfelipe, this has been fixed in the version 2.0.0-rc.40, by https://github.com/vtex/styleguide/pull/100. Please update and let us know if it persists.
